-- ======================================================================
--  IRON LEAGUE — the bounty pool
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing already logged is touched.
--
--  GENERATED by tools/build_bounties.py, which lifts every function below
--  straight out of supabase/schema.sql. Edit tools/bounty_pool.py or
--  schema.sql and re-run it — never edit this file.
--
--  What changes:
--    · the pool grows to 110 quests, including short ones worth a flat 20
--      points that take under three minutes, so a busy week still scores
--    · a bounty can now ask for points from one muscle group only — pulling
--      day, cardio day, iron day — and nothing else counts toward it
--    · which quest runs in a week becomes a shuffle of the whole pool,
--      reseeded every year, instead of week-number modulo 52
--    · you can pin a chosen quest to a chosen week, and write your own,
--      from the control room
-- ======================================================================
begin;

-- ------------------------------------------------------------ the pool ---
delete from public.bounties where idx >= 110;

insert into public.bounties (idx, name, descr, points, spec) values
(0,'DAWN PRESS','40 push-ups before 09:00',30,'{"reqs":[{"ex":"pushups","mode":"reps","min":40,"to_h":9}]}'),
(1,'CENTURY PUSH','100 push-ups across the day',40,'{"reqs":[{"ex":"pushups","mode":"reps","min":100}]}'),
(2,'DIP MASTER','30 dips',40,'{"reqs":[{"ex":"dips","mode":"reps","min":30}]}'),
(3,'DIP CENTURY','50 dips',50,'{"reqs":[{"ex":"dips","mode":"reps","min":50}]}'),
(4,'INVERTED WORLD','60 seconds of handstand hold',40,'{"reqs":[{"ex":"handstand","mode":"seconds","min":60}]}'),
(5,'CEILING PRESS','5 handstand push-ups',35,'{"reqs":[{"ex":"handstand","mode":"reps","min":5}]}'),
(6,'LUNCH PRESS','30 push-ups between 12:00 and 14:00',25,'{"reqs":[{"ex":"pushups","mode":"reps","min":30,"from_h":12,"to_h":14}]}'),
(7,'NIGHTCAP PUSH','40 push-ups after 20:00',30,'{"reqs":[{"ex":"pushups","mode":"reps","min":40,"from_h":20}]}'),
(8,'CLOCK PUNCHER','10 push-ups in each of 5 different hours',40,'{"kind":"hourly","ex":"pushups","each":10,"hours":5}'),
(9,'SPLIT CENTURY','50 push-ups before noon and 50 after',40,'{"kind":"split","ex":"pushups","min":50}'),
(10,'FIRST PULL','10 pull-ups before 10:00',30,'{"reqs":[{"ex":"pullups","mode":"reps","min":10,"to_h":10}]}'),
(11,'ROW COLLECTOR','50 inverted rows',40,'{"reqs":[{"ex":"rows","mode":"reps","min":50}]}'),
(12,'PULL CENTURY','30 pull-ups across the day',50,'{"reqs":[{"ex":"pullups","mode":"reps","min":30}]}'),
(13,'BAR SURGE','20 pull-ups',35,'{"reqs":[{"ex":"pullups","mode":"reps","min":20}]}'),
(14,'PULL AND ROW','15 pull-ups and 30 rows',45,'{"reqs":[{"ex":"pullups","mode":"reps","min":15},{"ex":"rows","mode":"reps","min":30}]}'),
(15,'MIDDAY PULL','15 pull-ups between 12:00 and 15:00',30,'{"reqs":[{"ex":"pullups","mode":"reps","min":15,"from_h":12,"to_h":15}]}'),
(16,'SKILL WORK','3 muscle-ups, or a 10 second flag hold',50,'{"kind":"any","any":[{"ex":"muscleup","mode":"reps","min":3},{"ex":"muscleup","mode":"seconds","min":10}]}'),
(17,'EVENING LATS','20 pull-ups after 18:00',35,'{"reqs":[{"ex":"pullups","mode":"reps","min":20,"from_h":18}]}'),
(18,'GREASE THE GROOVE','1 pull-up in each of 8 different hours',40,'{"kind":"hourly","ex":"pullups","each":1,"hours":8}'),
(19,'PULL DOUBLE','15 pull-ups before noon and 15 after',45,'{"kind":"split","ex":"pullups","min":15}'),
(20,'MORNING LEGS','100 air squats before 10:00',35,'{"reqs":[{"ex":"airsquats","mode":"reps","min":100,"to_h":10}]}'),
(21,'PISTOL PURSUIT','10 pistol squats',40,'{"reqs":[{"ex":"pistols","mode":"reps","min":10}]}'),
(22,'PISTOL BURNER','16 pistol squats',45,'{"reqs":[{"ex":"pistols","mode":"reps","min":16}]}'),
(23,'CORE LOCK','2 minutes of plank',30,'{"reqs":[{"ex":"plank","mode":"minutes","min":2}]}'),
(24,'KNEE RAISE SURGE','60 knee raises',35,'{"reqs":[{"ex":"kneeraises","mode":"reps","min":60}]}'),
(25,'THE L','30 seconds of L-sit',35,'{"reqs":[{"ex":"lsit","mode":"seconds","min":30}]}'),
(26,'SQUAT CENTURY','100 air squats',30,'{"reqs":[{"ex":"airsquats","mode":"reps","min":100}]}'),
(27,'AFTERNOON LEGS','80 air squats between 13:00 and 17:00',30,'{"reqs":[{"ex":"airsquats","mode":"reps","min":80,"from_h":13,"to_h":17}]}'),
(28,'CORE AND SQUAT','50 air squats and 30 knee raises',35,'{"reqs":[{"ex":"airsquats","mode":"reps","min":50},{"ex":"kneeraises","mode":"reps","min":30}]}'),
(29,'TWIST AND PISTOL','60 Russian twists and 6 pistol squats',40,'{"reqs":[{"ex":"twists","mode":"reps","min":60},{"ex":"pistols","mode":"reps","min":6}]}'),
(30,'EARLY RUN','3 km before 09:00',35,'{"reqs":[{"ex":"run","mode":"km","min":3,"to_h":9}]}'),
(31,'BIKE TOUR','10 km on the bike',35,'{"reqs":[{"ex":"bike","mode":"km","min":10}]}'),
(32,'SPRINT FINISHER','10 sprints',35,'{"reqs":[{"ex":"sprints","mode":"reps","min":10}]}'),
(33,'LUNCH WALK','3 km walk between 11:00 and 14:00',25,'{"reqs":[{"ex":"walk","mode":"km","min":3,"from_h":11,"to_h":14}]}'),
(34,'POOL SESSION','30 minutes of swimming',40,'{"reqs":[{"ex":"swim","mode":"minutes","min":30}]}'),
(35,'FIVE K','Run 5 km',40,'{"reqs":[{"ex":"run","mode":"km","min":5}]}'),
(36,'DOUBLE MOBILITY','Two separate stretching sessions',25,'{"reqs":[{"ex":"stretch","mode":"flat","min":2}]}'),
(37,'NIGHT WALK','4 km walk after 19:00',30,'{"reqs":[{"ex":"walk","mode":"km","min":4,"from_h":19}]}'),
(38,'SWIM AND STRETCH','20 minutes swimming and a stretching session',35,'{"reqs":[{"ex":"swim","mode":"minutes","min":20},{"ex":"stretch","mode":"flat","min":1}]}'),
(39,'CYCLE CENTURY','15 km on the bike',40,'{"reqs":[{"ex":"bike","mode":"km","min":15}]}'),
(40,'MORNING DISTANCE','4 km run or 12 km bike before 11:00',40,'{"kind":"any","any":[{"ex":"run","mode":"km","min":4,"to_h":11},{"ex":"bike","mode":"km","min":12,"to_h":11}]}'),
(41,'FULL BODY TRIAD','30 push-ups, 15 pull-ups and 30 air squats',45,'{"reqs":[{"ex":"pushups","mode":"reps","min":30},{"ex":"pullups","mode":"reps","min":15},{"ex":"airsquats","mode":"reps","min":30}]}'),
(42,'DUO SYNC','Train within an hour of somebody else in the league',30,'{"kind":"duo"}'),
(43,'IRON TRIFECTA','20 dips, 10 pull-ups and 50 air squats',45,'{"reqs":[{"ex":"dips","mode":"reps","min":20},{"ex":"pullups","mode":"reps","min":10},{"ex":"airsquats","mode":"reps","min":50}]}'),
(44,'UNDERDOG BOOST','Last in the league this week? Log anything today',50,'{"kind":"underdog"}'),
(45,'MINI MURPH','1.5 km run, 30 push-ups, 15 pull-ups, 45 air squats',60,'{"reqs":[{"ex":"run","mode":"km","min":1.5},{"ex":"pushups","mode":"reps","min":30},{"ex":"pullups","mode":"reps","min":15},{"ex":"airsquats","mode":"reps","min":45}]}'),
(46,'MIDDAY MADNESS','Two different exercises between 12:00 and 13:00',30,'{"kind":"distinct","what":"ex","min":2,"from_h":12,"to_h":13}'),
(47,'CENTURY CLUB','100 reps spread across 3 different exercises',40,'{"kind":"reps_across","exercises":3,"min":100}'),
(48,'PERSONAL RECORD','Beat your own best single day of points',50,'{"kind":"pr"}'),
(49,'TEAM SURGE','If 4 of you log today, everybody scores',30,'{"kind":"team","members":4}'),
(50,'TRIPLE THREAT','Train three different muscle groups today',40,'{"kind":"distinct","what":"cat","min":3}'),
(51,'NIGHT OWL','Two different exercises after 21:00',25,'{"kind":"distinct","what":"ex","min":2,"from_h":21}'),
(52,'MINUTE OF PUSH','As many push-ups as you can in one minute — 30 or more',20,'{"reqs":[{"ex":"pushups","mode":"reps","min":30}]}'),
(53,'THREE-MINUTE PLANK','Three minutes of plank, in as many goes as you like',20,'{"reqs":[{"ex":"plank","mode":"minutes","min":3}]}'),
(54,'SIXTY SQUATS','Sixty air squats — under two minutes if you keep moving',20,'{"reqs":[{"ex":"airsquats","mode":"reps","min":60}]}'),
(55,'DEAD HANG','Ninety seconds hanging from a bar',20,'{"reqs":[{"ex":"deadhang","mode":"seconds","min":90}]}'),
(56,'TEN PULL','Ten pull-ups. That is the whole bounty',20,'{"reqs":[{"ex":"pullups","mode":"reps","min":10}]}'),
(57,'WALL SIT','Two minutes in a wall sit',20,'{"reqs":[{"ex":"wallsit","mode":"seconds","min":120}]}'),
(58,'ROPE MINUTE','Five minutes of skipping',20,'{"reqs":[{"ex":"jumprope","mode":"minutes","min":5}]}'),
(59,'STAIR SPRINT','Five minutes of stairs',20,'{"reqs":[{"ex":"stairs","mode":"minutes","min":5}]}'),
(60,'HOLLOW HOLD','Ninety seconds of hollow hold',20,'{"reqs":[{"ex":"hollowhold","mode":"seconds","min":90}]}'),
(61,'BURST OF DIPS','Twenty dips, any bar or bench',20,'{"kind":"any","any":[{"ex":"dips","mode":"reps","min":20},{"ex":"benchdips","mode":"reps","min":30}]}'),
(62,'FORTY CRUNCH','Forty crunches',20,'{"reqs":[{"ex":"crunches","mode":"reps","min":40}]}'),
(63,'TWO MINUTES OF ANYTHING','Any two minutes of held work — plank, hang, wall sit or L-sit',20,'{"kind":"any","any":[{"ex":"plank","mode":"minutes","min":2},{"ex":"deadhang","mode":"seconds","min":120},{"ex":"wallsit","mode":"seconds","min":120},{"ex":"lsit","mode":"seconds","min":120}]}'),
(64,'PUSH DAY','60 points of pushing and nothing else counts',45,'{"kind":"cat_points","cat":"PUSH","min":60}'),
(65,'PULL DAY','50 points of pulling and nothing else counts',45,'{"kind":"cat_points","cat":"PULL","min":50}'),
(66,'LEG DAY','60 points of legs and nothing else counts',45,'{"kind":"cat_points","cat":"LEGS","min":60}'),
(67,'CORE DAY','45 points of core and nothing else counts',40,'{"kind":"cat_points","cat":"CORE","min":45}'),
(68,'ENDURANCE ONLY','50 points of cardio and nothing else counts',45,'{"kind":"cat_points","cat":"CARDIO","min":50}'),
(69,'IRON ONLY','60 points under a bar — gym lifts only',50,'{"kind":"cat_points","cat":"GYM","min":60}'),
(70,'PLAY DAY','40 points from a sport',40,'{"kind":"cat_points","cat":"SPORT","min":40}'),
(71,'UPPER LOCK','40 points of push and 40 of pull, same day',55,'{"kind":"cats","cats":[{"cat":"PUSH","min":40},{"cat":"PULL","min":40}]}'),
(72,'TWO HUNDRED','200 push-ups across the day',60,'{"reqs":[{"ex":"pushups","mode":"reps","min":200}]}'),
(73,'ARCHER''S DAY','30 archer push-ups',45,'{"reqs":[{"ex":"archerpush","mode":"reps","min":30}]}'),
(74,'PIKE POWER','40 pike push-ups',40,'{"reqs":[{"ex":"pikepush","mode":"reps","min":40}]}'),
(75,'CLAP IT OUT','25 clapping push-ups',45,'{"reqs":[{"ex":"clappush","mode":"reps","min":25}]}'),
(76,'RING WORK','25 ring dips',50,'{"reqs":[{"ex":"ringdips","mode":"reps","min":25}]}'),
(77,'CHIN COLLECTOR','40 chin-ups',50,'{"reqs":[{"ex":"chinups","mode":"reps","min":40}]}'),
(78,'TOES TO BAR','30 toes to bar',45,'{"reqs":[{"ex":"toestobar","mode":"reps","min":30}]}'),
(79,'FRONT LEVER HOLD','20 seconds of front lever, any tuck',50,'{"reqs":[{"ex":"frontlever","mode":"seconds","min":20}]}'),
(80,'DRAGON','15 dragon flags',50,'{"reqs":[{"ex":"dragonflag","mode":"reps","min":15}]}'),
(81,'PISTOL DUEL','20 pistol squats',45,'{"reqs":[{"ex":"pistols","mode":"reps","min":20}]}'),
(82,'NORDIC NIGHT','12 nordic curls',50,'{"reqs":[{"ex":"nordic","mode":"reps","min":12}]}'),
(83,'JUMP DAY','80 jump squats',45,'{"reqs":[{"ex":"jumpsquats","mode":"reps","min":80}]}'),
(84,'LUNGE MILE','120 lunges',45,'{"reqs":[{"ex":"lunges","mode":"reps","min":120}]}'),
(85,'BRIDGE BUILDER','100 glute bridges',35,'{"reqs":[{"ex":"gluteBridge","mode":"reps","min":100}]}'),
(86,'ROLLOUT','30 ab rollouts',40,'{"reqs":[{"ex":"rollout","mode":"reps","min":30}]}'),
(87,'SIDE ON','Three minutes of side plank, both sides',35,'{"reqs":[{"ex":"sideplank","mode":"minutes","min":3}]}'),
(88,'SUPERMAN','80 supermans',30,'{"reqs":[{"ex":"supermans","mode":"reps","min":80}]}'),
(89,'BICYCLE RACE','150 bicycle crunches',35,'{"reqs":[{"ex":"bicycle","mode":"reps","min":150}]}'),
(90,'CLIMBER','200 mountain climbers',35,'{"reqs":[{"ex":"mountainclimb","mode":"reps","min":200}]}'),
(91,'TEN K','Ten kilometres on foot, running or walking',55,'{"kind":"any","any":[{"ex":"run","mode":"km","min":10},{"ex":"walk","mode":"km","min":12}]}'),
(92,'LONG RIDE','25 km on a bike',45,'{"reqs":[{"ex":"bike","mode":"km","min":25}]}'),
(93,'POOL LENGTHS','45 minutes in the water',45,'{"reqs":[{"ex":"swim","mode":"minutes","min":45}]}'),
(94,'ROW HARD','20 minutes on the rower',40,'{"reqs":[{"ex":"row","mode":"minutes","min":20}]}'),
(95,'ON THE WALL','40 minutes of climbing',45,'{"reqs":[{"ex":"climbing","mode":"minutes","min":40}]}'),
(96,'GLOVES ON','30 minutes of boxing',40,'{"reqs":[{"ex":"boxing","mode":"minutes","min":30}]}'),
(97,'BENCH DAY','30 reps of barbell bench press',45,'{"reqs":[{"ex":"gymbench","mode":"reps","min":30}]}'),
(98,'SQUAT RACK','40 barbell squats',45,'{"reqs":[{"ex":"gymsquat","mode":"reps","min":40}]}'),
(99,'PULL THE FLOOR','20 deadlifts',50,'{"reqs":[{"ex":"gymdeadlift","mode":"reps","min":20}]}'),
(100,'SEVEN HOURS','One set in each of 7 different hours',50,'{"kind":"hourly","ex":"pushups","each":5,"hours":7}'),
(101,'SUNRISE AND SUNSET','30 pull-ups before noon and 30 after',50,'{"kind":"split","ex":"pullups","min":30}'),
(102,'FIVE WAYS','Train five different muscle groups',50,'{"kind":"distinct","what":"cat","min":5}'),
(103,'TEN EXERCISES','Ten different exercises in one day',45,'{"kind":"distinct","what":"ex","min":10}'),
(104,'SPREAD THE LOAD','300 reps across at least 6 exercises',55,'{"kind":"reps_across","exercises":6,"min":300}'),
(105,'BEAT YESTERDAY','Score more points today than on any day before it',45,'{"kind":"pr"}'),
(106,'SIX OF YOU','Six people in the league log something today',45,'{"kind":"team","members":6}'),
(107,'FULL HOUSE','Ten people in the league log something today',60,'{"kind":"team","members":10}'),
(108,'TRAINING PARTNER','Log within an hour of somebody else in the league',35,'{"kind":"duo"}'),
(109,'BACK FROM THE DEAD','Bottom of the table and still turned up',40,'{"kind":"underdog"}')
on conflict (idx) do update
  set name = excluded.name, descr = excluded.descr,
      points = excluded.points, spec = excluded.spec;

-- --------------------------------------------------------- bounty_schedule ---
create table if not exists public.bounty_schedule (
  week_start date primary key,
  bounty_idx int  not null references public.bounties(idx) on delete cascade,
  note       text,
  set_at     timestamptz not null default now()
);
alter table public.bounty_schedule enable row level security;
drop policy if exists bounty_schedule_read on public.bounty_schedule;
create policy bounty_schedule_read on public.bounty_schedule
  for select to authenticated using (true);

-- ------------------------------------------------------- bounty_cat_points ---
create or replace function public.bounty_cat_points(
  p_profile uuid, p_league uuid, p_cat text, p_day date) returns numeric
language sql stable set search_path = public as $$
  select coalesce(sum(w.points), 0)
  from public.workouts w
  where w.profile_id = p_profile
    and w.league_id  = p_league
    and (w.created_at at time zone public.app_timezone())::date = p_day
    and public.exercise_category(w.exercise_key) = p_cat
$$;

-- ------------------------------------------------------------- bounty_done ---
create or replace function public.bounty_done(
  p_profile uuid, p_league uuid, p_spec jsonb, p_day date) returns boolean
language plpgsql stable set search_path = public as $$
declare
  tz   text := public.app_timezone();
  kind text := coalesce(p_spec->>'kind', 'reqs');
  r    jsonb;
  n    int;
begin
  if kind = 'cat_points' then
    return public.bounty_cat_points(p_profile, p_league, p_spec->>'cat', p_day)
           >= (p_spec->>'min')::numeric;

  elsif kind = 'cats' then
    for r in select * from jsonb_array_elements(p_spec->'cats') loop
      if public.bounty_cat_points(p_profile, p_league, r->>'cat', p_day)
         < (r->>'min')::numeric then return false; end if;
    end loop;
    return true;

  elsif kind = 'reqs' then
    for r in select * from jsonb_array_elements(p_spec->'reqs') loop
      if not public.bounty_req(p_profile, p_league, r, p_day) then return false; end if;
    end loop;
    return true;

  elsif kind = 'any' then
    for r in select * from jsonb_array_elements(p_spec->'any') loop
      if public.bounty_req(p_profile, p_league, r, p_day) then return true; end if;
    end loop;
    return false;

  elsif kind = 'distinct' then
    select count(distinct case when p_spec->>'what' = 'cat'
                               then public.exercise_category(w.exercise_key)
                               else w.exercise_key end)
      into n
    from public.workouts w
    where w.profile_id = p_profile and w.league_id = p_league
      and (w.created_at at time zone tz)::date = p_day
      and (p_spec->>'from_h' is null or
           extract(hour from (w.created_at at time zone tz)) >= (p_spec->>'from_h')::int)
      and (p_spec->>'to_h' is null or
           extract(hour from (w.created_at at time zone tz)) <  (p_spec->>'to_h')::int);
    return coalesce(n, 0) >= (p_spec->>'min')::int;

  elsif kind = 'reps_across' then
    select count(distinct w.exercise_key) into n
    from public.workouts w
    where w.profile_id = p_profile and w.league_id = p_league
      and w.mode = 'reps' and (w.created_at at time zone tz)::date = p_day;
    if coalesce(n, 0) < (p_spec->>'exercises')::int then return false; end if;
    return (select coalesce(sum(w.amount), 0) from public.workouts w
            where w.profile_id = p_profile and w.league_id = p_league
              and w.mode = 'reps' and (w.created_at at time zone tz)::date = p_day)
           >= (p_spec->>'min')::numeric;

  elsif kind = 'split' then
    return public.bounty_req(p_profile, p_league,
             jsonb_build_object('ex', p_spec->>'ex', 'min', p_spec->>'min', 'to_h', 12), p_day)
       and public.bounty_req(p_profile, p_league,
             jsonb_build_object('ex', p_spec->>'ex', 'min', p_spec->>'min', 'from_h', 12), p_day);

  elsif kind = 'hourly' then
    select count(*) into n from (
      select extract(hour from (w.created_at at time zone tz)) as h, sum(w.amount) as a
      from public.workouts w
      where w.profile_id = p_profile and w.league_id = p_league
        and w.exercise_key = p_spec->>'ex'
        and (w.created_at at time zone tz)::date = p_day
      group by 1
    ) t where t.a >= (p_spec->>'each')::numeric;
    return coalesce(n, 0) >= (p_spec->>'hours')::int;

  elsif kind = 'pr' then
    return (select coalesce(sum(w.points), 0) from public.workouts w
            where w.profile_id = p_profile and w.league_id = p_league
              and (w.created_at at time zone tz)::date = p_day)
         > coalesce((select max(d.p) from (
             select (w.created_at at time zone tz)::date as d, sum(w.points) as p
             from public.workouts w
             where w.profile_id = p_profile and w.league_id = p_league
               and (w.created_at at time zone tz)::date < p_day
             group by 1) d), 0);

  elsif kind = 'team' then
    select count(distinct w.profile_id) into n
    from public.workouts w
    where w.league_id = p_league and (w.created_at at time zone tz)::date = p_day;
    return coalesce(n, 0) >= (p_spec->>'members')::int;

  elsif kind = 'duo' then
    return exists (
      select 1 from public.workouts a
      join public.workouts b on b.league_id = a.league_id
                            and b.profile_id <> a.profile_id
                            and abs(extract(epoch from (b.created_at - a.created_at))) <= 3600
      where a.profile_id = p_profile and a.league_id = p_league
        and (a.created_at at time zone tz)::date = p_day);

  elsif kind = 'underdog' then
    if not exists (select 1 from public.workouts w
                   where w.profile_id = p_profile and w.league_id = p_league
                     and (w.created_at at time zone tz)::date = p_day) then
      return false;
    end if;
    return (select coalesce(sum(w.points), 0) from public.workouts w
            where w.profile_id = p_profile and w.league_id = p_league
              and w.week_start = date_trunc('week', p_day)::date)
        <= (select min(t.p) from (
              select w.profile_id, coalesce(sum(w.points), 0) as p
              from public.workouts w
              where w.league_id = p_league
                and w.week_start = date_trunc('week', p_day)::date
                and exists (select 1 from public.workouts x
                            where x.profile_id = w.profile_id and x.league_id = p_league
                              and (x.created_at at time zone tz)::date = p_day)
              group by w.profile_id) t);
  end if;
  return false;
end $$;

-- ------------------------------------------------------------ bounty_index ---
create or replace function public.bounty_index(p_week date) returns int
language sql stable set search_path = public as $$
  with n as (select count(*)::int as total from public.bounties),
       y as (select extract(isoyear from p_week)::int as yr,
                    extract(week    from p_week)::int as wk),
       shuffled as (
         select b.idx,
                (row_number() over (order by md5((select yr from y)::text
                                                 || ':' || b.idx::text)) - 1)::int as slot
         from public.bounties b)
  select s.idx from shuffled s
  where s.slot = ((select wk from y) - 1) % greatest((select total from n), 1)
$$;

-- ------------------------------------------------------------- bounty_pick ---
create or replace function public.bounty_pick(p_week date) returns int
language sql stable set search_path = public as $$
  select coalesce((select bounty_idx from public.bounty_schedule
                   where week_start = p_week),
                  public.bounty_index(p_week))
$$;

-- ---------------------------------------------------- builtin_bounty_count ---
create or replace function public.builtin_bounty_count() returns int
language sql immutable set search_path = public as $$ select 110 $$;

-- ------------------------------------------------------ week_bounty_points ---
create or replace function public.week_bounty_points(p_league uuid, p_week date)
returns table (profile_id uuid, bounty numeric)
language sql stable set search_path = public as $$
  with b as (select * from public.bounties where idx = public.bounty_pick(p_week)),
       d as (select public.bounty_date(p_week) as day)
  select m.profile_id, (select points from b)::numeric
  from public.league_members m
  where m.league_id = p_league
    and (select count(*) from b) = 1
    and public.bounty_done(m.profile_id, p_league, (select spec from b), (select day from d))
$$;

-- ---------------------------------------------------------- current_bounty ---
create or replace function public.current_bounty(p_league uuid)
returns table (idx int, name text, descr text, points numeric,
               on_date date, mine boolean, winners int, first_name text,
               first_avatar text)
language sql stable security definer set search_path = public as $$
  with wk as (select public.current_week_start() as w),
       b  as (select * from public.bounties where idx = public.bounty_pick((select w from wk))),
       d  as (select public.bounty_date((select w from wk)) as day),
       done as (select profile_id from public.week_bounty_points(p_league, (select w from wk))),
       firsts as (
         select w2.profile_id, min(w2.created_at) as t
         from public.workouts w2
         where w2.league_id = p_league
           and (w2.created_at at time zone public.app_timezone())::date = (select day from d)
           and w2.profile_id in (select profile_id from done)
         group by 1 order by 2 limit 1)
  select b.idx, b.name, b.descr, b.points, (select day from d),
         exists (select 1 from done where profile_id = public.my_profile_id()),
         (select count(*)::int from done),
         (select p.display_name from firsts f join public.profiles p on p.id = f.profile_id),
         (select p.avatar from firsts f join public.profiles p on p.id = f.profile_id)
  from b
  where public.is_member(p_league)
$$;

-- ---------------------------------------------------------- admin_schedule ---
create or replace function public.admin_schedule()
returns table (week_start date, bounty_idx int, name text, descr text,
               points numeric, pinned boolean, note text)
language sql stable security definer set search_path = public as $$
  with weeks as (
    select (public.current_week_start() + (n * 7))::date as w
    from generate_series(0, 25) n)
  select k.w, public.bounty_pick(k.w), b.name, b.descr, b.points,
         exists (select 1 from public.bounty_schedule s where s.week_start = k.w),
         (select note from public.bounty_schedule s where s.week_start = k.w)
  from weeks k
  join public.bounties b on b.idx = public.bounty_pick(k.w)
  where public.is_admin()
  order by k.w
$$;

-- ---------------------------------------------------------- admin_bounties ---
create or replace function public.admin_bounties()
returns table (idx int, name text, descr text, points numeric, spec jsonb,
               runs_on date, custom boolean)
language sql stable security definer set search_path = public as $$
  with weeks as (
    select (public.current_week_start() + (n * 7))::date as w
    from generate_series(0, 51) n),
  built as (select max(idx) as top from public.bounties)
  select b.idx, b.name, b.descr, b.points, b.spec,
         (select min(w) from weeks where public.bounty_pick(w) = b.idx),
         b.idx >= public.builtin_bounty_count()
  from public.bounties b
  where public.is_admin()
  order by b.idx
$$;

-- -------------------------------------------------------- admin_pin_bounty ---
create or replace function public.admin_pin_bounty(p_week date, p_idx int, p_note text default null)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  if p_week < public.current_week_start() then
    raise exception 'That week has already been played';
  end if;
  if p_week <> date_trunc('week', p_week)::date then
    raise exception 'Pin a Monday — a bounty week starts on one';
  end if;
  if not exists (select 1 from public.bounties where idx = p_idx) then
    raise exception 'No bounty has that number';
  end if;
  insert into public.bounty_schedule (week_start, bounty_idx, note)
  values (p_week, p_idx, nullif(btrim(coalesce(p_note, '')), ''))
  on conflict (week_start) do update
    set bounty_idx = excluded.bounty_idx, note = excluded.note, set_at = now();
end $$;

-- ------------------------------------------------------ admin_unpin_bounty ---
create or replace function public.admin_unpin_bounty(p_week date)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  delete from public.bounty_schedule where week_start = p_week;
end $$;

-- -------------------------------------------------------- admin_add_bounty ---
create or replace function public.admin_add_bounty(
  p_name text, p_descr text, p_points numeric,
  p_ex text, p_mode text, p_min numeric,
  p_from_h int default null, p_to_h int default null)
returns int language plpgsql security definer set search_path = public as $$
declare next_idx int; req jsonb;
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  if char_length(btrim(coalesce(p_name, ''))) < 3 then
    raise exception 'Give it a name';
  end if;
  if p_points is null or p_points < 5 or p_points > 100 then
    raise exception 'Points must be between 5 and 100';
  end if;
  if not exists (select 1 from public.exercises e
                 where e.key = p_ex and e.modes ? p_mode) then
    raise exception 'That exercise cannot be logged that way';
  end if;
  if p_min is null or p_min <= 0 then raise exception 'Set an amount'; end if;
  if p_from_h is not null and (p_from_h < 0 or p_from_h > 23) then
    raise exception 'An hour is 0 to 23';
  end if;
  if p_to_h is not null and (p_to_h < 1 or p_to_h > 24) then
    raise exception 'An hour is 1 to 24';
  end if;

  req := jsonb_strip_nulls(jsonb_build_object(
    'ex', p_ex, 'mode', p_mode, 'min', p_min,
    'from_h', p_from_h, 'to_h', p_to_h));
  select coalesce(max(idx), -1) + 1 into next_idx from public.bounties;
  insert into public.bounties (idx, name, descr, points, spec)
  values (next_idx, upper(btrim(p_name)), btrim(coalesce(p_descr, '')), p_points,
          jsonb_build_object('reqs', jsonb_build_array(req)));
  return next_idx;
end $$;

-- ----------------------------------------------------- admin_delete_bounty ---
create or replace function public.admin_delete_bounty(p_idx int)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  if p_idx < public.builtin_bounty_count() then
    raise exception 'A built-in bounty cannot be deleted, only left unpinned';
  end if;
  delete from public.bounties where idx = p_idx;
end $$;

-- -------------------------------------------------------------- grants ---
revoke all on function public.bounty_pick(date)             from public, anon;
revoke all on function public.bounty_cat_points(uuid,uuid,text,date) from public, anon;
revoke all on function public.admin_schedule()              from public, anon;
revoke all on function public.admin_bounties()              from public, anon;
revoke all on function public.admin_pin_bounty(date,int,text) from public, anon;
revoke all on function public.admin_unpin_bounty(date)      from public, anon;
revoke all on function public.admin_add_bounty(text,text,numeric,text,text,numeric,int,int)
  from public, anon;
revoke all on function public.admin_delete_bounty(int)      from public, anon;
grant execute on function public.admin_schedule()              to authenticated;
grant execute on function public.admin_bounties()              to authenticated;
grant execute on function public.admin_pin_bounty(date,int,text) to authenticated;
grant execute on function public.admin_unpin_bounty(date)      to authenticated;
grant execute on function public.admin_add_bounty(text,text,numeric,text,text,numeric,int,int)
  to authenticated;
grant execute on function public.admin_delete_bounty(int)      to authenticated;
grant execute on function public.builtin_bounty_count()        to authenticated;
grant execute on function public.bounty_pick(date)             to authenticated;
grant execute on function public.bounty_cat_points(uuid,uuid,text,date) to authenticated;
grant select on public.bounty_schedule to authenticated;

commit;
