-- ======================================================================
--  IRON LEAGUE — the catch-up day, and five more places in a league
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_catchup.py, which lifts every function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  THE CATCH-UP DAY
--  One day a week, chosen per league, where being behind is worth something.
--  Everything logged that day is multiplied by how far off the lead you were
--  at the moment you logged it:
--
--      under 150 behind   x1.00
--      200                x1.06
--      300                x1.17
--      400                x1.29
--      500 or more        x1.40
--
--  It is not a handicap. The leader still trains and still scores every
--  point they earn; they simply score at x1.00 like anybody within touching
--  distance. Nobody loses anything, ever, and the most it can be worth is
--  forty per cent. It exists so somebody who missed four days has a reason
--  to turn up on Sunday instead of writing the week off.
--
--  The multiplier is stamped on the row as it is written, so it never
--  changes afterwards: two people logging the same set an hour apart can
--  legitimately score differently, and both keep what they earned.
--
--  A league starts with no catch-up day at all. It cannot be a rest day.
--
--  FIVE MORE PLACES
--  A league holds 35 instead of 30, and the leagues that already exist are
--  widened to match.
-- ======================================================================
begin;

-- ------------------------------------------------------- the new columns ---
alter table public.leagues
  add column if not exists catchup_dow int;
do $$ begin
  alter table public.leagues add constraint leagues_catchup_sane
    check (catchup_dow is null or catchup_dow between 1 and 7);
exception when duplicate_object then null;
end $$;

alter table public.workouts
  add column if not exists boost numeric not null default 1;
do $$ begin
  alter table public.workouts add constraint workouts_boost_check
    check (boost between 1 and 3);
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------- five more places -----
alter table public.leagues drop constraint if exists leagues_max_members_check;
update public.leagues set max_members = 35 where max_members = 30;
alter table public.leagues
  add constraint leagues_max_members_check check (max_members between 2 and 35);


-- ---------------------------------------------- shapes that changed ---
-- create-or-replace cannot change what a function returns, and it cannot
-- add a parameter either, so these two go first and are rebuilt below.
drop function if exists public.my_leagues() cascade;
drop function if exists public.set_league_settings(uuid, int[], int) cascade;

-- --------------------------------------------------------- catchup_floor ---
create or replace function public.catchup_floor()   returns numeric
language sql immutable set search_path = public as $$ select 150::numeric $$;

-- ------------------------------------------------------- catchup_ceiling ---
create or replace function public.catchup_ceiling() returns numeric
language sql immutable set search_path = public as $$ select 500::numeric $$;

-- ----------------------------------------------------------- catchup_max ---
create or replace function public.catchup_max()     returns numeric
language sql immutable set search_path = public as $$ select 1.40::numeric $$;

-- -------------------------------------------------------- is_catchup_day ---
create or replace function public.is_catchup_day(p_league uuid) returns boolean
language sql stable set search_path = public as $$
  select coalesce(
    (select l.catchup_dow from public.leagues l where l.id = p_league)
      = extract(isodow from (now() at time zone public.app_timezone()))::int,
    false)
$$;

-- ---------------------------------------------------- catchup_multiplier ---
create or replace function public.catchup_multiplier(p_league uuid, p_profile uuid)
returns numeric language sql stable set search_path = public as $$
  with tot as (
    select w.profile_id, coalesce(sum(w.points), 0) as p
    from public.workouts w
    where w.league_id = p_league
      and w.week_start = public.current_week_start()
    group by 1),
  best as (select coalesce(max(p), 0) as top from tot),
  mine as (select coalesce((select p from tot where profile_id = p_profile), 0) as p),
  gap  as (select greatest((select top from best) - (select p from mine), 0) as g)
  select round(
    1 + (public.catchup_max() - 1)
        * least(greatest((select g from gap) - public.catchup_floor(), 0)
                / (public.catchup_ceiling() - public.catchup_floor()), 1)
  , 2)
$$;

-- -------------------------------------------------------- workouts_stamp ---
create or replace function public.workouts_stamp() returns trigger
language plpgsql set search_path = public as $$
begin
  new.created_at := now();
  new.week_start := public.current_week_start();
  perform public.rest_day_check(new.profile_id, new.league_id,
                                new.exercise_key, new.created_at, null);
  if public.is_rest_day(new.league_id) then
    new.amount := 1;                       -- one session, no stacking
  end if;
  new.points := public.calc_points(new.exercise_key, new.mode, new.amount,
                                   new.bodyweight, new.load);
  -- On a catch-up day, what this is worth depends on how far behind you were
  -- when you logged it. Stamped now, so it never changes afterwards and the
  -- board never re-reads it: two people logging the same set an hour apart
  -- can legitimately score differently, and both keep what they earned.
  if public.is_catchup_day(new.league_id) then
    new.boost  := public.catchup_multiplier(new.league_id, new.profile_id);
    new.points := round(new.points * new.boost, 2);
  end if;
  if new.points <= 0 then
    if (select cat = 'GYM' from public.exercises where key = new.exercise_key) then
      raise exception 'A gym lift needs your bodyweight (30-250 kg) and the weight lifted (0-500 kg)';
    end if;
    raise exception 'Unknown exercise or unit (% / %)', new.exercise_key, new.mode;
  end if;
  return new;
end $$;

-- --------------------------------------------------- set_league_settings ---
create or replace function public.set_league_settings(
  p_league uuid, p_rest_dow int[], p_season_weeks int,
  p_catchup_dow int default null)
returns public.leagues language plpgsql security definer set search_path = public as $$
declare me uuid := public.my_profile_id(); row public.leagues;
begin
  if me is null then raise exception 'NO_PROFILE'; end if;
  if not exists (select 1 from public.leagues where id = p_league and owner_id = me) then
    raise exception 'Only the person who created a league can change its settings';
  end if;
  if p_rest_dow is not null and exists (
      select 1 from unnest(p_rest_dow) d where d < 1 or d > 7) then
    raise exception 'Rest days must be weekday numbers 1 to 7';
  end if;
  if array_length(p_rest_dow, 1) > 3 then
    raise exception 'At most three rest days a week';
  end if;
  if p_catchup_dow is not null and (p_catchup_dow < 1 or p_catchup_dow > 7) then
    raise exception 'A catch-up day is a weekday number 1 to 7';
  end if;
  -- A rest day closes the league, so it cannot also be the day being behind
  -- is worth something. One or the other.
  if p_catchup_dow is not null and p_catchup_dow = any (coalesce(p_rest_dow, '{}'::int[])) then
    raise exception 'The catch-up day cannot also be a rest day';
  end if;
  update public.leagues
     set rest_dow = coalesce(p_rest_dow, rest_dow), season_weeks = p_season_weeks,
         catchup_dow = p_catchup_dow
   where id = p_league returning * into row;
  return row;
end $$;

-- ------------------------------------------------------------ my_leagues ---
create or replace function public.my_leagues()
returns table (id uuid, name text, code text, owner_id uuid, members int,
               max_members int, joined_at timestamptz,
               badge jsonb, rest_dow int[], season_weeks int, catchup_dow int,
               created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select l.id, l.name, l.code, l.owner_id,
         (select count(*)::int from public.league_members m2 where m2.league_id = l.id),
         l.max_members, m.joined_at,
         l.badge, l.rest_dow, l.season_weeks, l.catchup_dow, l.created_at
  from public.leagues l
  join public.league_members m on m.league_id = l.id
  where m.profile_id = public.my_profile_id()
  order by m.joined_at
$$;

-- the stamp trigger is recreated with the function it calls
drop trigger if exists workouts_stamp_trg on public.workouts;
create trigger workouts_stamp_trg
  before insert on public.workouts
  for each row execute function public.workouts_stamp();

-- -------------------------------------------------------- grants ---
revoke all on function public.is_catchup_day(uuid)          from public, anon;
revoke all on function public.catchup_multiplier(uuid,uuid) from public, anon;
grant execute on function public.set_league_settings(uuid,int[],int,int) to authenticated;
grant execute on function public.is_catchup_day(uuid)           to authenticated;
grant execute on function public.catchup_multiplier(uuid,uuid)  to authenticated;
grant execute on function public.catchup_floor()                to authenticated;
grant execute on function public.catchup_ceiling()              to authenticated;
grant execute on function public.catchup_max()                  to authenticated;

commit;
