-- ======================================================================
--  IRON LEAGUE — the cup
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED, no points
--  are rewritten, and nothing already live changes shape — this file only
--  adds.
--
--  GENERATED by tools/build_cup_migration.py, which lifts every function below
--  out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  The season table rewards turning up every week. That is the right thing to
--  reward and a quiet thing to watch: by week 30 the top of the table has
--  usually been the top of the table for a month, and the arithmetic says so
--  before the week starts.
--
--  WHAT IT IS
--  A straight knockout for the top of the season, played over its last four
--  weeks, where one bad week ends you however good the year has been.
--
--      · the field is the top 16 of the season — 8 or 4 in a league that
--        cannot fill 16, and no cup at all under 4
--      · the bracket APPEARS ten weeks before the final, drawn from the season
--        table as it stands, so a ninth place can see they would draw the
--        eighth seed and a seventeenth can see exactly what they are missing
--      · it LOCKS four weeks out: whatever the table says then is the draw
--      · then one round a week — round of 16, quarters, semis, final — with
--        the final in the season's last week, so the cup and the table finish
--        together
--
--  A tie is won on the points you score in that league in that week: the same
--  number the weekly board already shows, so there is nothing extra to log and
--  nothing extra to understand. A dead heat goes to the higher seed, which is
--  what keeps the regular season worth playing beyond qualifying.
--
--  WHAT IT DOES NOT DO
--  It pays no season points. Silverware that moved the table would make the
--  last four weeks worth more than the first thirty-four, and the table is the
--  thing that keeps people going.
--
--  NOTHING IS STORED
--  The field, the seeding, every tie and every result are derived from
--  weekly_history on read, the way divisions, streaks, the repetition discount
--  and the season table already are. There is no bracket row to backfill, no
--  result to repair when a week is corrected, and a league that runs this
--  today has an honest cup rather than an invented one.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ------------------------------------------------------------ cup_window ---
create or replace function public.cup_window() returns int
language sql immutable set search_path = public as $fn$ select 10 $fn$;

-- ------------------------------------------------------------- cup_field ---
create or replace function public.cup_field(p_eligible int) returns int
language sql immutable set search_path = public as $fn$
  select case when coalesce(p_eligible, 0) >= 16 then 16
              when p_eligible >= 8 then 8
              when p_eligible >= 4 then 4
              else 0 end
$fn$;

-- -------------------------------------------------------- cup_seed_order ---
create or replace function public.cup_seed_order(p_field int) returns int[]
language plpgsql immutable set search_path = public as $fn$
declare ord int[] := array[1]; nxt int[]; i int; n int;
begin
  while array_length(ord, 1) < p_field loop
    n := array_length(ord, 1) * 2;
    nxt := '{}'::int[];
    for i in 1 .. array_length(ord, 1) loop
      nxt := nxt || ord[i] || (n + 1 - ord[i]);
    end loop;
    ord := nxt;
  end loop;
  return ord;
end $fn$;

-- -------------------------------------------------------- cup_round_name ---
create or replace function public.cup_round_name(p_round int, p_rounds int) returns text
language sql immutable set search_path = public as $fn$
  select case p_rounds - p_round
           when 0 then 'FINAL'
           when 1 then 'SEMI-FINALS'
           when 2 then 'QUARTER-FINALS'
           else 'ROUND OF ' || (2 ^ (p_rounds - p_round + 1))::int
         end
$fn$;

-- ------------------------------------------------------------- cup_seeds ---
create or replace function public.cup_seeds(p_league uuid, p_season int, p_before date)
returns table (seed int, profile_id uuid, display_name text, avatar text,
               points numeric)
language sql stable security definer set search_path = public as $fn$
  with wk as (
    select h.week_start, h.profile_id, h.display_name, h.avatar, h.joined_at,
           row_number() over (partition by h.week_start
                              order by h.points desc, h.joined_at asc)::int as rk
    from public.weekly_history(p_league) h
    where h.week_start < p_before
      and public.season_index(p_league, h.week_start) = p_season
  ),
  agg as (
    select w.profile_id, max(w.display_name) as nm, max(w.avatar) as av,
           sum(public.rank_points(w.rk))::numeric as pts,
           count(*) filter (where w.rk = 1) as wins,
           min(w.rk) as best, min(w.joined_at) as joined
    from wk w group by 1)
  select (row_number() over (order by a.pts desc, a.wins desc,
                                      a.best asc, a.joined asc))::int,
         a.profile_id, a.nm, a.av, a.pts
  from agg a
  where public.is_member(p_league)
$fn$;

-- ------------------------------------------------------ league_cup_state ---
create or replace function public.league_cup_state(p_league uuid, p_season int default null)
returns table (phase text, season int, seasons int, field int, rounds int,
               entrants int, lock_week date, first_week date, final_week date,
               round int, round_name text, week_start date, weeks_to_lock int,
               my_rank int, my_seed int, cut_points numeric)
language plpgsql stable security definer set search_path = public as $fn$
declare
  me uuid := public.my_profile_id();
  cw date := public.current_week_start();
  n int; brk int; cyc int; w0 date; idx int;
  seas int; lastw date; lockw date; firstw date;
  cnt int; fld int; rds int; ph text; rnd int; wk date; cut numeric;
  myrank int; myseed int;
begin
  if not public.is_member(p_league) then return; end if;
  select l.season_weeks, coalesce(l.season_break, 0) into n, brk
    from public.leagues l where l.id = p_league;
  -- A knockout needs a finish line to hang off, and a season short enough to
  -- be all cup is not a season: four weeks are the rounds and at least one has
  -- to be played before them or there is nothing to seed on.
  if n is null or n < 5 then return; end if;

  w0  := public.league_week0(p_league);
  cyc := n + brk;
  idx := greatest((cw - w0) / 7, 0);
  -- A break week belongs to the cycle it follows, so the cup that just
  -- finished keeps showing through the off-season instead of vanishing on the
  -- Monday after the final.
  seas  := coalesce(p_season, idx / cyc);
  lastw := w0 + (seas * cyc + n - 1) * 7;
  -- Fixed four weeks out, whatever the field turns out to be. It has to be
  -- fixed: if the lock date moved with the field size and the field size were
  -- read off the weeks before the lock date, neither would ever settle.
  lockw := lastw - 3 * 7;

  select count(*)::int into cnt from public.cup_seeds(p_league, seas, lockw);
  fld := public.cup_field(cnt);
  if fld = 0 then return; end if;
  rds := 0;
  while 2 ^ rds < fld loop rds := rds + 1; end loop;
  -- A smaller field needs fewer weeks, so it starts later and the final stays
  -- where it is.
  firstw := lastw - (rds - 1) * 7;

  if    cw > lastw                              then ph := 'DONE';
  elsif cw >= firstw                            then ph := 'RUNNING';
  elsif cw >= lastw - (public.cup_window() - 1) * 7 then ph := 'PROJECTED';
  else  return;                                 -- too early to be worth a tab
  end if;

  if ph = 'RUNNING' then
    rnd := ((cw - firstw) / 7) + 1;
    wk  := cw;
  end if;

  select s.seed, s.points into myseed, cut
    from public.cup_seeds(p_league, seas, lockw) s where s.profile_id = me;
  myrank := myseed;
  if myseed > fld then myseed := null; end if;
  -- what the last qualifying place is worth, so the tab can say how far off
  -- the cut somebody is rather than just that they are out
  select s.points into cut
    from public.cup_seeds(p_league, seas, lockw) s where s.seed = fld;

  return query select ph, seas, (idx / cyc) + 1, fld, rds, cnt,
                      lockw, firstw, lastw, rnd,
                      case when rnd is null then null
                           else public.cup_round_name(rnd, rds) end,
                      wk, greatest((lockw - cw) / 7, 0)::int,
                      myrank, myseed, cut;
end $fn$;

-- ------------------------------------------------------------ league_cup ---
create or replace function public.league_cup(p_league uuid, p_season int default null)
returns table (round int, round_name text, slot int,
               a_seed int, a_profile uuid, a_name text, a_avatar text,
               a_points numeric, a_from int[],
               b_seed int, b_profile uuid, b_name text, b_avatar text,
               b_points numeric, b_from int[],
               winner uuid, winner_seed int, status text, week_start date,
               mine boolean)
language plpgsql stable security definer set search_path = public as $fn$
declare
  me uuid := public.my_profile_id();
  cw date := public.current_week_start();
  st record;
  seedp uuid[]; seedn text[]; seeda text[];
  ord int[]; cur int[]; nxt int[];
  pts jsonb; r int; i int; blk int; wk date;
  sa int; sb int; pa numeric; pb numeric; wn int; stt text;
begin
  select * into st from public.league_cup_state(p_league, p_season);
  if st.phase is null then return; end if;

  select array_agg(s.profile_id order by s.seed),
         array_agg(s.display_name order by s.seed),
         array_agg(s.avatar order by s.seed)
    into seedp, seedn, seeda
    from public.cup_seeds(p_league, st.season, st.lock_week) s
   where s.seed <= st.field;

  -- Every cup week's points in one object, so a fifteen tie bracket does not
  -- run weekly_history fifteen times. The week in progress is not in there —
  -- it has not finished — so the live board supplies it and a tie being played
  -- right now shows a running score.
  select coalesce(jsonb_object_agg(k, v), '{}'::jsonb) into pts from (
    select h.profile_id::text || '|' || h.week_start::text as k, h.points as v
    from public.weekly_history(p_league) h
    where h.week_start >= st.first_week and h.week_start <= st.final_week
    union all
    select l.profile_id::text || '|' || cw::text, l.points
    from public.league_leaderboard(p_league, null) l
    where cw >= st.first_week and cw <= st.final_week) q;

  ord := public.cup_seed_order(st.field);
  cur := ord;
  for r in 1 .. st.rounds loop
    wk  := st.first_week + (r - 1) * 7;
    blk := (2 ^ (r - 1))::int;
    stt := case when wk < cw then 'DONE' when wk = cw then 'LIVE'
                else 'SCHEDULED' end;
    nxt := '{}'::int[];
    for i in 1 .. array_length(cur, 1) / 2 loop
      sa := cur[2 * i - 1];
      sb := cur[2 * i];
      pa := coalesce((pts ->> (seedp[sa]::text || '|' || wk::text))::numeric, 0);
      pb := coalesce((pts ->> (seedp[sb]::text || '|' || wk::text))::numeric, 0);
      -- A tie is settled only once its week is over. A dead heat goes to the
      -- higher seed: somebody has to go through, and the season is the fairest
      -- thing to break it on.
      if stt = 'DONE' and sa > 0 and sb > 0 then
        wn := case when pa > pb then sa when pb > pa then sb
                   else least(sa, sb) end;
      else
        wn := 0;
      end if;
      nxt := nxt || wn;
      return query select
        r, public.cup_round_name(r, st.rounds), i,
        nullif(sa, 0), seedp[sa], seedn[sa], seeda[sa],
        case when sa > 0 then pa end,
        ord[(2 * i - 2) * blk + 1 : (2 * i - 1) * blk],
        nullif(sb, 0), seedp[sb], seedn[sb], seeda[sb],
        case when sb > 0 then pb end,
        ord[(2 * i - 1) * blk + 1 : (2 * i) * blk],
        seedp[nullif(wn, 0)], nullif(wn, 0), stt, wk,
        (me is not null and me in (seedp[sa], seedp[sb]));
    end loop;
    cur := nxt;
  end loop;
end $fn$;

-- -------------------------------------------------------- grants ---
revoke all on function public.cup_window()                  from public, anon, authenticated;
revoke all on function public.cup_field(int)                from public, anon, authenticated;
revoke all on function public.cup_seed_order(int)           from public, anon, authenticated;
revoke all on function public.cup_round_name(int,int)       from public, anon, authenticated;
revoke all on function public.cup_seeds(uuid,int,date)      from public, anon, authenticated;
revoke all on function public.league_cup_state(uuid,int)    from public, anon;
revoke all on function public.league_cup(uuid,int)          from public, anon;
grant execute on function public.league_cup_state(uuid,int)    to authenticated;
grant execute on function public.league_cup(uuid,int)          to authenticated;

commit;

