-- ======================================================================
--  IRON LEAGUE — two totals in the control room instead of one
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_dashboard.py, which lifts the function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  WHY
--  The dashboard showed a player 720 where the app showed 706, and neither
--  was wrong. The dashboard column was lifetime: every workout ever logged,
--  counted once even when the same set fanned out to several leagues, and
--  with no bonus in it. The app was showing this week on one league board,
--  where the combo and bounty bonuses are added on top. One column called
--  "Points" cannot mean both, so there are now two:
--
--      lifetime      everything ever logged, once per log, no bonuses
--      week_points   what the league board reads this week, bonuses included
--
--  Nothing is recalculated and nothing is repaired, because nothing was
--  broken — the numbers simply now say which question they answer.
-- ======================================================================
begin;

-- create-or-replace cannot rename or add a returned column, so it goes first.
drop function if exists public.admin_players() cascade;


create or replace function public.admin_players()
returns table (id uuid, display_name text, avatar text, restore_code text,
               leagues int, workouts bigint, lifetime numeric, week_points numeric,
               last_log timestamptz, created_at timestamptz, is_admin boolean)
language sql stable security definer set search_path = public as $$
  with wk as (select public.current_week_start() as w),
  lg as (select distinct league_id from public.league_members),
  base as (
    select x.profile_id, x.league_id, sum(x.points) as pts
    from public.workouts x
    where x.week_start = (select w from wk)
    group by 1, 2),
  cb as (
    select l.league_id, c.profile_id, c.bonus
    from lg l, lateral public.week_combo_bonus(l.league_id, (select w from wk)) c),
  bb as (
    select l.league_id, b.profile_id, b.bounty
    from lg l, lateral public.week_bounty_points(l.league_id, (select w from wk)) b),
  board as (
    select m.profile_id,
           max(coalesce(base.pts, 0) + coalesce(cb.bonus, 0)
                                     + coalesce(bb.bounty, 0)) as total
    from public.league_members m
    left join base on base.profile_id = m.profile_id and base.league_id = m.league_id
    left join cb   on cb.profile_id   = m.profile_id and cb.league_id   = m.league_id
    left join bb   on bb.profile_id   = m.profile_id and bb.league_id   = m.league_id
    group by 1)
  select p.id, p.display_name, p.avatar, p.restore_code,
         (select count(*)::int from public.league_members m where m.profile_id = p.id),
         (select count(distinct w.group_id) from public.workouts w where w.profile_id = p.id),
         coalesce((select sum(points) from (
            select distinct on (group_id) group_id, points
            from public.workouts where profile_id = p.id
            order by group_id, league_id) x), 0),
         coalesce((select total from board where board.profile_id = p.id), 0)::numeric,
         (select max(w.created_at) from public.workouts w where w.profile_id = p.id),
         p.created_at, p.is_admin
  from public.profiles p
  where public.is_admin()
  order by p.created_at
$$;

-- -------------------------------------------------------- grants ---
grant execute on function public.admin_players()               to authenticated;

commit;
