-- ======================================================================
--  IRON LEAGUE — leaving a league, and being taken out of one
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED and no
--  points are rewritten.
--
--  GENERATED by tools/build_membership_migration.py, which lifts every
--  function below out of supabase/schema.sql. Edit there and re-run it,
--  never here.
--
--  WHAT CHANGES
--  · leave_league() now goes through drop_membership(), which handles the two
--    cases the old one-line delete did not.
--  · admin_memberships() lists who is in what, for the control room.
--  · admin_remove_member() takes one person out of one league. The account,
--    its restore code, its badges and everything it logged anywhere else are
--    untouched — this is the half of admin_delete_profile() that somebody
--    usually actually wants.
--
--  THE LEAGUE IS NEVER DELETED, even when the last member walks out.
--  leagues.id is the parent of workouts.league_id ON DELETE CASCADE, and a
--  workout is what a lifetime total is made of. Somebody who leaves their
--  only league to keep a quiet account must come back to the rank they
--  earned, not to zero. An empty league is invisible to everybody — my_leagues
--  only returns what you are a member of — and costs one row; the control room
--  can delete it when it really is rubbish.
--
--  IF THE OWNER LEAVES, the league goes to whoever has been in it longest, so
--  the settings and the crest never end up unreachable. If the owner was the
--  last one out they stay the owner of an empty league, which means rejoining
--  with the code hands it straight back.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ------------------------------------------------------- drop_membership ---
create or replace function public.drop_membership(p_league uuid, p_profile uuid)
returns void language plpgsql security definer set search_path = public as $fn$
declare own uuid; heir uuid;
begin
  delete from public.league_members
   where league_id = p_league and profile_id = p_profile;
  select owner_id into own from public.leagues where id = p_league;
  if own is distinct from p_profile then return; end if;
  select m.profile_id into heir from public.league_members m
   where m.league_id = p_league order by m.joined_at, m.profile_id limit 1;
  if heir is not null then
    update public.leagues set owner_id = heir where id = p_league;
  end if;
end $fn$;

-- ---------------------------------------------------------- leave_league ---
create or replace function public.leave_league(p_league uuid) returns void
language plpgsql security definer set search_path = public as $fn$
declare me uuid := public.my_profile_id();
begin
  if me is null then raise exception 'NO_PROFILE'; end if;
  perform public.drop_membership(p_league, me);
end $fn$;

-- ----------------------------------------------------- admin_memberships ---
create or replace function public.admin_memberships()
returns table (league_id uuid, league_name text, profile_id uuid,
               display_name text, joined_at timestamptz, is_owner boolean)
language sql stable security definer set search_path = public as $fn$
  select l.id, l.name, p.id, p.display_name, m.joined_at, l.owner_id = p.id
  from public.league_members m
  join public.leagues l on l.id = m.league_id
  join public.profiles p on p.id = m.profile_id
  where public.is_admin()
  order by l.name, m.joined_at
$fn$;

-- --------------------------------------------------- admin_remove_member ---
create or replace function public.admin_remove_member(p_league uuid, p_profile uuid)
returns void language plpgsql security definer set search_path = public as $fn$
begin
  if not public.is_admin() then raise exception 'Not allowed'; end if;
  if not exists (select 1 from public.league_members
                  where league_id = p_league and profile_id = p_profile) then
    raise exception 'That person is not in that league';
  end if;
  perform public.drop_membership(p_league, p_profile);
end $fn$;

-- -------------------------------------------------------- grants ---
revoke all on function public.leave_league(uuid)            from public, anon;
revoke all on function public.drop_membership(uuid,uuid)    from public, anon;
revoke all on function public.admin_memberships()           from public, anon;
revoke all on function public.admin_remove_member(uuid,uuid) from public, anon;
grant execute on function public.leave_league(uuid)            to authenticated;
grant execute on function public.admin_memberships()           to authenticated;
grant execute on function public.admin_remove_member(uuid,uuid) to authenticated;

commit;

