-- ======================================================================
--  IRON LEAGUE — how a league scores
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_scoring.py, which lifts every function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  Every league keeps scoring exactly as it does today. The column defaults
--  to 'hardcore', which is the behaviour that has always existed, so nothing
--  changes for anyone until somebody chooses otherwise for their own league.
--
--  HARDCORE   every rep counts the same, however many you do. Raw volume,
--             raw competition. This is what every league is now.
--
--  BALANCED   the first 40 points from ONE exercise on ONE day count in
--             full, 40 to 85 at 70%, past 85 at 40%. Time and distance work
--             gets twice the allowance, because you cannot farm a marathon.
--             Recovery is never tapered.
--
--             A fifteen-minute session loses about 3%. Three hours grinding
--             one movement loses about half. Varying the same effort across
--             two exercises is worth roughly a third more than putting it
--             all into one.
--
--  The taper reads base points only. Bounties, the daily combo and raids are
--  untouched, so the flat rewards a busy person can actually reach are worth
--  relatively more in a balanced league — which is the point.
-- ======================================================================
begin;

-- ------------------------------------------------------------ the column ---
alter table public.leagues
  add column if not exists scoring text not null default 'hardcore';

do $$ begin
  alter table public.leagues add constraint leagues_scoring_known
    check (scoring in ('hardcore', 'balanced'));
exception when duplicate_object then null;
end $$;


-- ---------------------------------------------- shapes that changed ---
-- create-or-replace cannot change what a function returns, so these go
-- first and are rebuilt below.
drop function if exists public.league_leaderboard(uuid, date) cascade;
drop function if exists public.my_leagues() cascade;

-- ------------------------------------------------------------ decay_full ---
create or replace function public.decay_full(p_cat text) returns numeric
language sql immutable set search_path = public as $$
  select case when p_cat in ('CARDIO', 'SPORT') then 80 else 40 end::numeric
$$;

-- ------------------------------------------------------------ decay_half ---
create or replace function public.decay_half(p_cat text) returns numeric
language sql immutable set search_path = public as $$
  select case when p_cat in ('CARDIO', 'SPORT') then 170 else 85 end::numeric
$$;

-- ---------------------------------------------------------- decay_points ---
create or replace function public.decay_points(p_points numeric, p_cat text) returns numeric
language sql immutable set search_path = public as $$
  select case
    when p_cat = 'RECOVERY' then p_points
    when p_points <= t.f then p_points
    when p_points <= t.h then t.f + (p_points - t.f) * 0.70
    else t.f + (t.h - t.f) * 0.70 + (p_points - t.h) * 0.40
  end
  from (select public.decay_full(p_cat) as f, public.decay_half(p_cat) as h) t
$$;

-- ------------------------------------------------------ week_base_points ---
create or replace function public.week_base_points(p_league uuid, p_week date)
returns table (profile_id uuid, base numeric, logged numeric)
language sql stable set search_path = public as $$
  with mode as (
    select coalesce((select scoring from public.leagues where id = p_league),
                    'hardcore') as m),
  per_day as (
    select w.profile_id,
           (w.created_at at time zone public.app_timezone())::date as d,
           w.exercise_key,
           public.exercise_category(w.exercise_key) as cat,
           sum(w.points) as pts
    from public.workouts w
    where w.league_id = p_league and w.week_start = p_week
    group by 1, 2, 3, 4)
  select profile_id,
         sum(case when (select m from mode) = 'balanced'
                  then public.decay_points(pts, cat)
                  else pts end)::numeric,
         sum(pts)::numeric
  from per_day
  group by 1
$$;

-- ---------------------------------------------------- league_leaderboard ---
create or replace function public.league_leaderboard(p_league uuid, p_week date default null)
returns table (profile_id uuid, display_name text, avatar text, points numeric,
               base_points numeric, bonus numeric, entries bigint,
               joined_at timestamptz, lifetime numeric, banner text,
               pinned_badges text[], name_color text, logged numeric)
language sql stable security definer set search_path = public as $$
  -- `lifetime` drives the rank banner on each row. Like divisions and duel
  -- records it is derived on read, so there is nothing to store or award.
  with wk as (select coalesce(p_week, public.current_week_start()) as w),
  cb as (select * from public.week_combo_bonus(p_league, (select w from wk))),
  bb as (select * from public.week_bounty_points(p_league, (select w from wk))),
  -- base points already have the league's scoring mode applied; `logged` is
  -- what was put in before any taper, so a row can show both
  wb as (select * from public.week_base_points(p_league, (select w from wk))),
  lt as (
    -- Lifetime follows the person, not the league. A log fans out to one row
    -- per league, so count each log once (by group_id) or joining a second
    -- league would double everyone's rank.
    select profile_id, sum(points) as total
    from (select distinct on (group_id) group_id, profile_id, points
          from public.workouts order by group_id, league_id) one_per_log
    group by profile_id)
  select p.id, p.display_name, p.avatar,
         (coalesce(max(wb.base), 0) + coalesce(max(cb.bonus), 0)
                                    + coalesce(max(bb.bounty), 0))::numeric,
         coalesce(max(wb.base), 0)::numeric,
         (coalesce(max(cb.bonus), 0) + coalesce(max(bb.bounty), 0))::numeric,
         count(w.id), m.joined_at,
         coalesce(max(lt.total), 0)::numeric, p.banner, p.pinned_badges,
         p.name_color, coalesce(max(wb.logged), 0)::numeric
  from public.league_members m
  join public.profiles p on p.id = m.profile_id
  left join public.workouts w
         on w.profile_id = p.id and w.league_id = p_league
        and w.week_start = (select w from wk)
  left join cb on cb.profile_id = p.id
  left join bb on bb.profile_id = p.id
  left join lt on lt.profile_id = p.id
  left join wb on wb.profile_id = p.id
  where m.league_id = p_league and public.is_member(p_league)
  group by p.id, p.display_name, p.avatar, p.banner, p.pinned_badges,
           p.name_color, m.joined_at
  order by 4 desc, 8 asc
$$;

-- -------------------------------------------------------- weekly_history ---
create or replace function public.weekly_history(p_league uuid)
returns table (week_start date, profile_id uuid, display_name text, avatar text,
               points numeric, entries bigint)
language sql stable security definer set search_path = public as $$
  -- Finished weeks are scored the same way the live board scores this one,
  -- so a league that taper volume does not have a history that does not.
  select t.week_start, t.profile_id, t.display_name, t.avatar,
         (t.pts + coalesce(cb.bonus, 0))::numeric, t.n
  from (
    select w.week_start, p.id as profile_id, p.display_name, p.avatar,
           coalesce((select wb.base from public.week_base_points(p_league, w.week_start) wb
                     where wb.profile_id = p.id), 0) as pts,
           count(*) as n
    from public.workouts w
    join public.profiles p on p.id = w.profile_id
    where w.league_id = p_league
      and w.week_start < public.current_week_start()
      and public.is_member(p_league)
    group by w.week_start, p.id, p.display_name, p.avatar
  ) t
  left join lateral (
    select bonus from public.week_combo_bonus(p_league, t.week_start) b
    where b.profile_id = t.profile_id
  ) cb on true
  order by t.week_start desc, 5 desc
$$;

-- ------------------------------------------------------------ my_leagues ---
create or replace function public.my_leagues()
returns table (id uuid, name text, code text, owner_id uuid, members int,
               max_members int, joined_at timestamptz,
               badge jsonb, rest_dow int[], season_weeks int, scoring text,
               created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select l.id, l.name, l.code, l.owner_id,
         (select count(*)::int from public.league_members m2 where m2.league_id = l.id),
         l.max_members, m.joined_at,
         l.badge, l.rest_dow, l.season_weeks, l.scoring, l.created_at
  from public.leagues l
  join public.league_members m on m.league_id = l.id
  where m.profile_id = public.my_profile_id()
  order by m.joined_at
$$;

-- ---------------------------------------------------- set_league_scoring ---
create or replace function public.set_league_scoring(p_league uuid, p_mode text)
returns public.leagues language plpgsql security definer set search_path = public as $$
declare me uuid := public.my_profile_id(); row public.leagues;
begin
  if me is null then raise exception 'NO_PROFILE'; end if;
  if not exists (select 1 from public.leagues where id = p_league and owner_id = me) then
    raise exception 'Only the person who created a league can change how it scores';
  end if;
  if p_mode not in ('hardcore', 'balanced') then
    raise exception 'A league scores either hardcore or balanced';
  end if;
  update public.leagues set scoring = p_mode
   where id = p_league returning * into row;
  return row;
end $$;

-- -------------------------------------------------------- grants ---
revoke all on function public.decay_points(numeric,text)    from public, anon;
revoke all on function public.decay_full(text)              from public, anon;
revoke all on function public.decay_half(text)              from public, anon;
revoke all on function public.week_base_points(uuid,date)   from public, anon;
revoke all on function public.set_league_scoring(uuid,text) from public, anon;
grant execute on function public.decay_points(numeric,text)    to authenticated;
grant execute on function public.decay_full(text)              to authenticated;
grant execute on function public.decay_half(text)              to authenticated;
grant execute on function public.week_base_points(uuid,date)   to authenticated;
grant execute on function public.set_league_scoring(uuid,text) to authenticated;

commit;
