-- ======================================================================
--  IRON LEAGUE — a season range on the stats tab
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED and no points
--  are rewritten.
--
--  GENERATED by tools/build_stats_migration.py, which lifts both functions
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  The stats tab offered THIS WEEK and ALL TIME. A season is the unit the
--  league actually plays in, and it had no tab — so "how is my season going"
--  could only be answered by the hall of fame table, which shows placings,
--  not what you lifted.
--
--  WHAT CHANGES
--  my_stats() and my_muscles() take a third argument, `p_from`, which bounds
--  the range below. null is the behaviour they already had.
--
--      week    p_all false, p_from null    this week, as before
--      season  p_all true,  p_from <date>  since the Monday the season opened
--      all     p_all true,  p_from null    the lot, as before
--
--  The date comes from league_season_state().first_week, so an off-season
--  shows the season that just closed rather than an empty tab.
--
--  THE PART THAT IS NOT OBVIOUS
--  A defaulted third parameter looks like it keeps an app that has not updated
--  working. It does not. PostgREST resolves a call by argument NAME, and both
--  the two-argument and the three-argument version accept `p_league` and
--  `p_all`, so an old app's call matches both and Postgres refuses it:
--
--      function public.my_stats(p_league => ..., p_all => ...) is not unique
--
--  So exactly one of them may be visible. This file moves the two-argument
--  version into a `retired` schema instead of dropping it: PostgREST does not
--  look there, the move is reversible, and — unlike a drop — the migration
--  channel this project applies through will actually run it. Both happen in
--  one transaction, so there is no instant where both are callable and no
--  instant where neither is.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ------------------------------------------------- somewhere to put it ---
-- Not exposed to PostgREST and no rights for anybody, so what lands here is
-- unreachable from an app while staying recoverable with one more ALTER.
create schema if not exists retired;
revoke all on schema retired from public;

-- -------------------------------------------------------------- my_stats ---
create or replace function public.my_stats(p_league uuid, p_all boolean default false,
                                p_from date default null)
returns table (exercise_key text, category text, mode text,
               total_amount numeric, total_points numeric, entries bigint,
               active_days bigint, raw_points numeric, cap numeric)
language sql stable security definer set search_path = public as $fn$
  with mine as (
    select w.exercise_key, w.mode, w.week_start, w.amount, w.points,
           (w.created_at at time zone public.app_timezone())::date as d
    from public.workouts w
    where w.league_id  = p_league
      and w.profile_id = public.my_profile_id()
      and (p_all or w.week_start = public.current_week_start())
      and (p_from is null or w.week_start >= p_from)
      and public.is_member(p_league)),
  -- the discount is per week, so a lifetime view sums its weeks rather than
  -- running one enormous pile through the curve
  wk as (
    select m.exercise_key, m.week_start, sum(m.points) as raw,
           coalesce(max(x.cap), public.cap_full()) as cap
    from mine m left join public.exercises x on x.key = m.exercise_key
    group by 1, 2),
  scored as (
    select exercise_key, sum(public.tier_points(raw, cap)) as pts,
           sum(raw) as raw, max(cap) as cap
    from wk group by 1)
  -- A handful of movements are logged in two units (a handstand in reps and
  -- in seconds). The budget is the exercise's, not the unit's, so the week's
  -- discount is shared between its rows in proportion to what each earned —
  -- otherwise one exercise's cap would be counted once per unit.
  select m.exercise_key, public.exercise_category(m.exercise_key), m.mode,
         sum(m.amount)::numeric,
         round(max(s.pts) * sum(m.points) / nullif(max(s.raw), 0), 2)::numeric,
         count(*), count(distinct m.d),
         sum(m.points)::numeric, max(s.cap)::numeric
  from mine m join scored s on s.exercise_key = m.exercise_key
  group by 1, 2, 3
  order by 5 desc
$fn$;

-- ------------------------------------------------------------ my_muscles ---
create or replace function public.my_muscles(p_league uuid, p_all boolean default false,
                                  p_from date default null)
returns table (key text, name text, view text, points numeric,
               pct numeric, target numeric, weeks int)
language sql stable security definer set search_path = public as $fn$
  with me as (select public.my_profile_id() as id),
  mine as (
    select w.exercise_key, w.points
    from public.workouts w
    where w.league_id = p_league and w.profile_id = (select id from me)
      and (p_all or w.week_start = public.current_week_start())
      and (p_from is null or w.week_start >= p_from)
  ),
  wk as (
    select greatest(count(distinct w.week_start), 1)::int as n
    from public.workouts w
    where w.league_id = p_league and w.profile_id = (select id from me)
      and (p_all or w.week_start = public.current_week_start())
      and (p_from is null or w.week_start >= p_from)
  ),
  dose as (select public.muscle_dose((select id from me)) as f),
  spread as (
    select s.key as mkey, sum(x.points * (s.value)::numeric) as pts
    from mine x
    join public.exercises e on e.key = x.exercise_key
    cross join lateral jsonb_each_text(e.muscles) as s(key, value)
    group by 1
  )
  select m.key, m.name, m.view,
         round(coalesce(sp.pts, 0), 1),
         public.muscle_charge(coalesce(sp.pts, 0),
                              m.target * (select f from dose) * (select n from wk)),
         round(m.target * (select f from dose) * (select n from wk))::numeric,
         (select n from wk)
  from public.muscles m
  left join spread sp on sp.mkey = m.key
  where public.is_member(p_league)
  order by m.sort, m.key
$fn$;

-- ------------------------------------------- and the old shapes, retired ---
do $mv$
declare r record; alias text;
begin
  for r in
    select p.oid as id, p.oid::regprocedure as sig, p.proname as nom
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and (p.proname, pg_get_function_identity_arguments(p.oid)) in (('my_stats', 'p_league uuid, p_all boolean'),
           ('my_muscles', 'p_league uuid, p_all boolean'))
  loop
    begin
      execute format('alter function %s set schema retired', r.sig);
    exception when duplicate_function then
      -- An older generated migration re-created the shape this file retires and
      -- a copy is already parked, so the obvious name is taken. Park this one
      -- under its own rather than leave it visible: a visible twin is what
      -- makes every call from an app that has not updated ambiguous.
      alias := r.nom || '_' || r.id::text;
      execute format('alter function %s rename to %I', r.sig, alias);
      execute format('alter function public.%I(%s) set schema retired',
                     alias, pg_get_function_identity_arguments(r.id));
    end;
    raise notice 'retired %', r.sig;
  end loop;
end $mv$;

-- -------------------------------------------------------- grants ---
revoke all on function public.my_stats(uuid,boolean,date)    from public, anon;
revoke all on function public.my_muscles(uuid,boolean,date)  from public, anon;
grant execute on function public.my_muscles(uuid,boolean,date) to authenticated;
grant execute on function public.my_stats(uuid,boolean,date)   to authenticated;

commit;

