-- ======================================================================
--  IRON LEAGUE — a season table instead of a race to five crowns
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. NOTHING LOGGED IS TOUCHED and no points are rewritten.
--
--  GENERATED by tools/build_season_migration.py, which lifts every function
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  People start and then fade. A week is a sprint and winning it is
--  all-or-nothing, so anybody who cannot realistically top the board has no
--  reason to care by Wednesday. The crowns race had the same hole: only a
--  winner ever moved, so "first to five" was a contest between the same two
--  or three people and wallpaper for everybody else.
--
--  WHAT CHANGES
--  Every finished week now pays out by FINISHING POSITION, the way a motor
--  racing season does, and the season adds it up:
--
--      1st  5.00     6th  1.60     11th 0.70     16th 0.27
--      2nd  3.60     7th  1.35     12th 0.60     17th 0.21
--      3rd  2.80     8th  1.15     13th 0.50     18th 0.16
--      4th  2.30     9th  1.00     14th 0.40     19th 0.13
--      5th  1.90    10th  0.85     15th 0.33     20th 0.10
--
--  21st and below score nothing, which is the one rung that has to hurt.
--
--  The shape is deliberate. A win is worth 39% more than second — the same
--  gap motor racing uses — so the top of the board still means something.
--  Below that it decays gently enough that climbing always pays: 16th to 11th
--  more than doubles your week, and tenth is a fifth of a win rather than a
--  rounding error. Over 38 weeks a perfect run is 190 and a steady tenth is
--  32: far apart, and both of them are a season.
--
--  THE SEASON
--  leagues.season_weeks already existed and did nothing but print itself. It
--  is the season length now, and its ceiling goes from 26 to 52 so a real
--  season fits — 38 for a football year, 50 for a calendar one. null is one
--  open season that never ends.
--
--  A season is counted in CALENDAR weeks from the Monday the league was
--  created, not in weeks that happened to have activity. A quiet week still
--  burns a week of the season; otherwise a league that goes dead for a month
--  would quietly extend its own season and the table would never close.
--
--  Weeks already played are in season 1 — there is nothing to backfill,
--  because the table is derived from weekly_history on read rather than
--  stored. Crowns still follow the person across every season.
--
--  WHAT GOES
--  The TRIPLE CROWN, FIVE CROWNS and TEN CROWNS badges. CHAMPION — win a
--  week — stays, because winning a week is still the thing.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ----------------------------------------- a real season has to fit ---
-- 26 weeks was the ceiling from when this column was a label and nothing read
-- it. A football season is 38 and a long one is 50.
alter table public.leagues drop constraint if exists leagues_season_sane;
alter table public.leagues add constraint leagues_season_sane
  check (season_weeks is null or season_weeks between 1 and 52);

-- A new league gets a football season unless its owner says otherwise. An
-- open-ended season has no finish line to play for, which is the whole point
-- of the table. Existing leagues keep whatever they already have.
alter table public.leagues alter column season_weeks set default 38;

-- ----------------------------------------------------------- rank_points ---
create or replace function public.rank_points(p_rank int) returns numeric
language sql immutable set search_path = public as $$
  select coalesce((array[
    5.00, 3.60, 2.80, 2.30, 1.90, 1.60, 1.35, 1.15, 1.00, 0.85,
    0.70, 0.60, 0.50, 0.40, 0.33, 0.27, 0.21, 0.16, 0.13, 0.10
  ]::numeric[])[p_rank], 0)
$$;

-- ---------------------------------------------------------- league_week0 ---
create or replace function public.league_week0(p_league uuid) returns date
language sql stable set search_path = public as $$
  select date_trunc('week',
           (l.created_at at time zone public.app_timezone()))::date
  from public.leagues l where l.id = p_league
$$;

-- ---------------------------------------------------------- season_index ---
create or replace function public.season_index(p_league uuid, p_week date) returns int
language sql stable set search_path = public as $$
  select case
    when (select l.season_weeks from public.leagues l where l.id = p_league) is null
      then 0                                 -- one season, never ending
    else greatest(((p_week - public.league_week0(p_league)) / 7)
                  / (select l.season_weeks from public.leagues l where l.id = p_league),
                  0)::int
  end
$$;

-- ---------------------------------------------------- league_season_info ---
create or replace function public.league_season_info(p_league uuid)
returns table (season int, seasons int, season_weeks int, weeks_done int,
               first_week date, last_week date)
language sql stable security definer set search_path = public as $$
  with wk as (
    select distinct h.week_start,
           public.season_index(p_league, h.week_start) as season
    from public.weekly_history(p_league) h
    where h.week_start < public.current_week_start()
  ),
  cur as (select coalesce(max(season), 0)::int as s from wk)
  select (select s from cur),
         greatest((select count(distinct season)::int from wk), 1),
         (select l.season_weeks from public.leagues l where l.id = p_league),
         (select count(*)::int from wk where season = (select s from cur)),
         (select min(week_start) from wk where season = (select s from cur)),
         (select max(week_start) from wk where season = (select s from cur))
  where public.is_member(p_league)
$$;

-- --------------------------------------------------------- league_season ---
create or replace function public.league_season(p_league uuid, p_season int default null)
returns table (profile_id uuid, display_name text, avatar text, banner text,
               pinned_badges text[], name_color text, points numeric,
               weeks int, wins int, best_rank int, lifetime_wins int,
               mine boolean)
language sql stable security definer set search_path = public as $$
  with ranked as (
    select h.week_start, h.profile_id,
           row_number() over (partition by h.week_start
                              order by h.points desc, h.joined_at asc)::int as rk,
           public.season_index(p_league, h.week_start) as season
    from public.weekly_history(p_league) h
    where h.week_start < public.current_week_start()
  ),
  pick as (select coalesce(p_season, (select max(season) from ranked), 0)::int as s),
  season_rows as (select * from ranked where season = (select s from pick)),
  -- crowns follow the person across every season, so the row can still say
  -- what somebody has done here in total
  life as (select profile_id, count(*)::int n from ranked where rk = 1 group by 1)
  select p.id, p.display_name, p.avatar, p.banner, p.pinned_badges, p.name_color,
         coalesce(sum(public.rank_points(sr.rk)), 0)::numeric,
         count(sr.week_start)::int,
         (count(sr.week_start) filter (where sr.rk = 1))::int,
         min(sr.rk),
         coalesce(max(lf.n), 0)::int,
         p.id = public.my_profile_id()
  from public.league_members m
  join public.profiles p on p.id = m.profile_id
  left join season_rows sr on sr.profile_id = p.id
  left join life lf on lf.profile_id = p.id
  where m.league_id = p_league and public.is_member(p_league)
  group by p.id, p.display_name, p.avatar, p.banner, p.pinned_badges,
           p.name_color, m.joined_at
  order by 7 desc, 9 desc, 10 asc nulls last, m.joined_at
$$;

-- ------------------------------------------------------------- my_badges ---
create or replace function public.my_badges(p_league uuid)
returns table (key text, name text, descr text, earned boolean,
               progress numeric, target numeric)
language sql stable security definer set search_path = public as $$
  with me as (select public.my_profile_id() as id),
  wins as (
    select count(*)::numeric n from (
      select h.week_start, h.profile_id,
             row_number() over (partition by h.week_start
                                order by h.points desc, h.joined_at asc) rk
      from public.weekly_history(p_league) h
      where h.week_start < public.current_week_start()
    ) x where x.rk = 1 and x.profile_id = (select id from me)
  ),
  strk as (select best_streak from public.league_streaks(p_league)
           where profile_id = (select id from me)),
  life as (
    select coalesce((select sum(public.tier_points(raw, cap)) from (
             select sum(w.points) as raw, max(x.cap) as cap
             from public.workouts w
             left join public.exercises x on x.key = w.exercise_key
             where w.league_id = p_league and w.profile_id = (select id from me)
             group by w.week_start, w.exercise_key) t), 0) as pts,
           (select count(*)::numeric from public.workouts
            where league_id = p_league and profile_id = (select id from me)) as logs),
  duels as (select coalesce(won, 0)::numeric as w
            from public.my_duel_record(p_league) limit 1),
  cats as (select count(distinct public.exercise_category(exercise_key))::numeric as n
           from public.workouts
           where league_id = p_league and profile_id = (select id from me)),
  gymn as (select count(*)::numeric n from public.workouts w
           join public.exercises e on e.key = w.exercise_key
           where w.league_id = p_league and w.profile_id = (select id from me)
             and e.cat = 'GYM'),
  km as (select coalesce(sum(amount), 0)::numeric n from public.workouts
         where league_id = p_league and profile_id = (select id from me)
           and exercise_key in ('run','walk','bike') and mode = 'km'),
  -- The weakest region on the figure, this week and at its best ever. One
  -- number, because the point of the figure is the part you are neglecting:
  -- your balance is your worst muscle, and no amount of curling raises it.
  bal as (select coalesce(min(pct), 0) as now
          from public.my_muscles(p_league, false)),
  balbest as (
    select coalesce(max(worst), 0) as best from (
      select w.week_start,
             min(public.muscle_charge(coalesce(sp.pts, 0),
                 m.target * public.muscle_dose((select id from me)))) as worst
      from public.muscles m
      cross join (select distinct week_start from public.workouts
                  where league_id = p_league and profile_id = (select id from me)) w
      left join lateral (
        select sum(x.points * (s.value)::numeric) as pts
        from public.workouts x
        join public.exercises e on e.key = x.exercise_key
        cross join lateral jsonb_each_text(e.muscles) as s(key, value)
        where x.league_id = p_league and x.profile_id = (select id from me)
          and x.week_start = w.week_start and s.key = m.key
      ) sp on true
      group by w.week_start) z
  ),
  b(key, name, descr, progress, target) as (values
    ('week_win','CHAMPION','Win a week in this league', (select n from wins), 1::numeric),
    ('balance40','NO WEAK LINK','Every muscle past 40% in one week',
      (select best from balbest), 40),
    ('balance100','FULLY FORGED','A full week on all fourteen at once',
      (select best from balbest), 100),
    ('streak7','SEVEN STRAIGHT','Seven days running above 20 points',
      (select coalesce(max(best_streak),0)::numeric from strk), 7),
    ('streak14','FORTNIGHT','Fourteen days running',
      (select coalesce(max(best_streak),0)::numeric from strk), 14),
    ('streak30','UNBROKEN','Thirty days running',
      (select coalesce(max(best_streak),0)::numeric from strk), 30),
    ('duel3','DUELLIST','Win three duels', (select w from duels), 3),
    ('duel10','GLADIATOR','Win ten duels', (select w from duels), 10),
    ('century','CENTURION','A hundred logged sets here', (select logs from life), 100),
    ('grand','FIVE THOUSAND','Five thousand points here', (select pts from life), 5000),
    ('allrounder','ALL ROUNDER','Train all five muscle groups', (select n from cats), 5),
    ('gym','IRON PLATE','Fifty gym sets', (select n from gymn), 50),
    ('runner','DISTANCE','A hundred kilometres covered', (select n from km), 100)
  )
  select b.key, b.name, b.descr,
         coalesce(b.progress, 0) >= b.target,
         least(coalesce(b.progress, 0), b.target), b.target
  from b
  order by (coalesce(b.progress,0) >= b.target) desc,
           coalesce(b.progress,0) / nullif(b.target,0) desc
$$;

-- -------------------------------------------------------- grants ---
grant execute on function public.rank_points(int)              to authenticated;
grant execute on function public.league_week0(uuid)            to authenticated;
grant execute on function public.season_index(uuid,date)       to authenticated;
grant execute on function public.league_season_info(uuid)      to authenticated;
grant execute on function public.league_season(uuid,int)       to authenticated;
grant execute on function public.my_badges(uuid)               to authenticated;

commit;

