#!/usr/bin/env python3
"""Write supabase/dashboard-points.sql from schema.sql.

The control room's player table used to carry one column called "Points",
which was lifetime, deduped across leagues and free of every bonus. Read next
to a league board it looked like the app was losing points. The function now
returns both numbers under names that say which is which, so the migration
has to drop it first: create-or-replace cannot change what a function returns.

Usage:  python3 tools/build_dashboard.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "dashboard-points.sql")

WANTED = ("admin_players",)

HEAD = """-- ======================================================================
--  IRON LEAGUE — two totals in the control room instead of one
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_dashboard.py, which lifts the function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  WHY
--  The dashboard showed a player 720 where the app showed 706, and neither
--  was wrong. The dashboard column was lifetime: every workout ever logged,
--  counted once even when the same set fanned out to several leagues, and
--  with no bonus in it. The app was showing this week on one league board,
--  where the combo and bounty bonuses are added on top. One column called
--  "Points" cannot mean both, so there are now two:
--
--      lifetime      everything ever logged, once per log, no bonuses
--      week_points   what the league board reads this week, bonuses included
--
--  Nothing is recalculated and nothing is repaired, because nothing was
--  broken — the numbers simply now say which question they answer.
-- ======================================================================
begin;

-- create-or-replace cannot rename or add a returned column, so it goes first.
drop function if exists public.admin_players() cascade;

"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD, lift(schema, "function", "admin_players") + "\n",
             "-- -------------------------------------------------------- grants ---",
             grants(schema, WANTED), "\ncommit;"]
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
