#!/usr/bin/env python3
"""Write the bounty seed into both places it has to exist, from one source.

  · supabase/schema.sql        the paste-and-run rebuild
  · supabase/bounty-pool.sql   the migration for a database already running

It validates first: every exercise key must exist in the bank, every mode
must be one the exercise actually offers, every category must be real, and
no two bounties may share a name. A bounty that names an exercise nobody
can log is a bounty nobody can ever complete.

Usage:  python3 tools/build_bounties.py
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from bounty_pool import POOL                                    # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
MIGRATION = os.path.join(ROOT, "supabase", "bounty-pool.sql")
BANK = os.path.join(HERE, "exercises.json")

CATS = {"PUSH", "PULL", "LEGS", "CORE", "CARDIO", "SPORT", "GYM", "RECOVERY"}
KINDS = {"reqs", "any", "distinct", "cat_points", "cats", "reps_across",
         "split", "hourly", "pr", "team", "duo", "underdog"}


def bank():
    items = json.load(open(BANK))
    return {x["key"]: x for x in items}


def check(pool, ex):
    """Every claim a bounty makes must be one the app can actually satisfy."""
    problems = []
    names = {}
    for i, (name, descr, points, spec) in enumerate(pool):
        where = "#%d %s" % (i, name)
        if name in names:
            problems.append("%s: name already used at #%d" % (where, names[name]))
        names[name] = i
        if not 5 <= points <= 100:
            problems.append("%s: %d points is outside 5…100" % (where, points))

        kind = spec.get("kind", "reqs")
        if kind not in KINDS:
            problems.append("%s: unknown kind %r" % (where, kind))
            continue

        reqs = []
        if kind == "reqs":
            reqs = spec.get("reqs", [])
            if not reqs:
                problems.append("%s: no requirements" % where)
        elif kind == "any":
            reqs = spec.get("any", [])
            if len(reqs) < 2:
                problems.append("%s: 'any' with fewer than two options" % where)
        elif kind in ("split", "hourly"):
            reqs = [{"ex": spec.get("ex"), "mode": "reps"}]
        elif kind == "cat_points":
            if spec.get("cat") not in CATS:
                problems.append("%s: %r is not a muscle group" % (where, spec.get("cat")))
        elif kind == "cats":
            for c in spec.get("cats", []):
                if c.get("cat") not in CATS:
                    problems.append("%s: %r is not a muscle group" % (where, c.get("cat")))

        for r in reqs:
            key = r.get("ex")
            if key is None:
                continue
            if key not in ex:
                problems.append("%s: no such exercise %r" % (where, key))
                continue
            mode = r.get("mode")
            if mode and mode not in ex[key]["modes"]:
                problems.append("%s: %s cannot be logged in %s (only %s)"
                                % (where, key, mode, "/".join(sorted(ex[key]["modes"]))))
    return problems


def sql_rows(pool):
    out = []
    for i, (name, descr, points, spec) in enumerate(pool):
        out.append("(%d,%s,%s,%d,%s)"
                   % (i, q(name), q(descr), points,
                      q(json.dumps(spec, separators=(",", ":")))))
    return ",\n".join(out)


def q(text):
    return "'" + str(text).replace("'", "''") + "'"


HEAD = """-- The bounty pool: %d side quests. One is drawn each week; which one is a
-- deterministic shuffle of the whole pool, reseeded every year, so no two
-- years run the same order and nothing repeats inside a year.
--
-- GENERATED by tools/build_bounties.py from tools/bounty_pool.py — edit
-- there and re-run, never here.
"""


def stamp_count(n):
    """builtin_bounty_count() must equal the pool, or a generated bounty could
    be deleted from the control room as if somebody had written it."""
    s = open(SCHEMA, encoding="utf-8").read()
    fixed = re.sub(r"(create function public\.builtin_bounty_count\(\) returns int\n"
                   r"language sql immutable set search_path = public as \$\$ select )\d+",
                   r"\g<1>%d" % n, s)
    if fixed != s:
        open(SCHEMA, "w", encoding="utf-8").write(fixed)


def write_schema(pool):
    s = open(SCHEMA, encoding="utf-8").read()
    start = s.index("insert into public.bounties (idx, name, descr, points, spec) values")
    end = s.index(";\n", start) + 2
    block = (HEAD % len(pool)
             + "insert into public.bounties (idx, name, descr, points, spec) values\n"
             + sql_rows(pool) + ";\n")
    open(SCHEMA, "w", encoding="utf-8").write(s[:start] + block + s[end:])
    return len(block.splitlines())


from sqllift import lift, grants                                 # noqa: E402


MIGRATION_OBJECTS = [
    ("table", "bounty_schedule"),
    ("function", "bounty_cat_points"),
    ("function", "bounty_done"),
    ("function", "bounty_index"),
    ("function", "bounty_pick"),
    ("function", "builtin_bounty_count"),
    ("function", "week_bounty_points"),
    ("function", "current_bounty"),
    ("function", "admin_schedule"),
    ("function", "admin_bounties"),
    ("function", "admin_pin_bounty"),
    ("function", "admin_unpin_bounty"),
    ("function", "admin_add_bounty"),
    ("function", "admin_delete_bounty"),
]


def write_migration(pool):
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [MIGRATION_HEAD % {"count": len(pool)}]
    parts.append("-- ------------------------------------------------------------ the pool ---")
    parts.append("delete from public.bounties where idx >= %d;\n" % len(pool))
    parts.append("insert into public.bounties (idx, name, descr, points, spec) values")
    parts.append(sql_rows(pool))
    parts.append("on conflict (idx) do update\n"
                 "  set name = excluded.name, descr = excluded.descr,\n"
                 "      points = excluded.points, spec = excluded.spec;\n")
    for kind, name in MIGRATION_OBJECTS:
        parts.append("-- " + ("-" * (72 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, kind, name) + "\n")
    parts.append("-- -------------------------------------------------------------- grants ---")
    parts.append(grants(schema))
    parts.append("\ncommit;")
    body = "\n".join(parts) + "\n"
    open(MIGRATION, "w", encoding="utf-8").write(body)
    return len(body.splitlines())


MIGRATION_HEAD = """-- ======================================================================
--  IRON LEAGUE — the bounty pool
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing already logged is touched.
--
--  GENERATED by tools/build_bounties.py, which lifts every function below
--  straight out of supabase/schema.sql. Edit tools/bounty_pool.py or
--  schema.sql and re-run it — never edit this file.
--
--  What changes:
--    · the pool grows to %(count)d quests, including short ones worth a flat 20
--      points that take under three minutes, so a busy week still scores
--    · a bounty can now ask for points from one muscle group only — pulling
--      day, cardio day, iron day — and nothing else counts toward it
--    · which quest runs in a week becomes a shuffle of the whole pool,
--      reseeded every year, instead of week-number modulo 52
--    · you can pin a chosen quest to a chosen week, and write your own,
--      from the control room
-- ======================================================================
begin;
"""


def main():
    ex = bank()
    problems = check(POOL, ex)
    if problems:
        print("The pool does not hold up:")
        for p in problems:
            print("  ·", p)
        sys.exit(1)

    stamp_count(len(POOL))
    n1 = write_schema(POOL)
    n2 = write_migration(POOL)
    print("%d bounties validated" % len(POOL))
    print("  schema.sql seed    : %d lines" % n1)
    print("  bounty-pool.sql    : %d lines" % n2)


if __name__ == "__main__":
    main()
