#!/usr/bin/env python3
"""Write supabase/repetition-cap.sql from schema.sql.

One movement now gets cheaper as the week fills. The first `cap` points of an
exercise in a week pay in full, the next `cap` pay half, everything after that
pays a quarter — and it never reaches zero, so no total is capped and nobody
is ever told to stop.

Nothing is stamped and nothing is rewritten. workouts.points stays exactly
what the movement is worth; every board derives the discount on read, the way
divisions, streaks and rivalries already do. That means the migration adds a
column and replaces functions, and touches not one logged row.

Usage:  python3 tools/build_cap_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
SEED = os.path.join(ROOT, "tools", "exercises.sql")
OUT = os.path.join(ROOT, "supabase", "repetition-cap.sql")

# create-or-replace cannot change what a function returns, and my_stats gained
# two columns.
RESHAPED = [("my_stats", "p_league uuid, p_all boolean")]

# tier_points first: everything below calls it. check_function_bodies is off
# for the same reason schema.sql turns it off — these reference each other and
# Postgres resolves a SQL body at create time.
OBJECTS = ["cap_full", "tier_points", "exercise_cap", "week_scored",
           "life_scored_all", "catchup_multiplier", "league_leaderboard",
           "weekly_history", "my_badges", "muscle_dose", "my_stats",
           "admin_players"]

WANTED = ("cap_full", "tier_points", "exercise_cap", "week_scored",
          "life_scored_all", "catchup_multiplier", "league_leaderboard",
          "weekly_history", "my_badges", "muscle_dose", "my_stats",
          "admin_players")

HEAD = """-- ======================================================================
--  IRON LEAGUE — one movement gets cheaper as the week fills
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. NOT ONE LOGGED ROW IS TOUCHED OR REWRITTEN.
--
--  GENERATED by tools/build_cap_migration.py, which lifts every function
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  Points are linear in reps but effort is not. The ceiling on a hard
--  movement is what a body can do; the ceiling on an easy one is only
--  boredom. So the cheapest thing a person can repeat forever was always the
--  best points per hour, and it showed: one member's step-ups came to seven
--  per cent of an entire league's week, and push-ups alone were sixteen.
--
--  WHAT CHANGES
--  The first `cap` points of ONE exercise in ONE week pay in full, the next
--  `cap` pay half, everything past that pays a quarter:
--
--      scored = min(raw, cap)
--             + max(min(raw, 2*cap) - cap, 0) * 0.5
--             + max(raw - 2*cap, 0)          * 0.25
--
--  It never reaches zero. No total is capped, nobody is ever told to stop,
--  and more work is always more points — repeating one movement simply stops
--  being the best way to score, and the best move left is to do something
--  else. That is the whole variety rule; there is no separate bonus, because
--  a bonus large enough to matter only ever pays the people already scoring
--  the most.
--
--  THE NUMBERS
--  The default cap is 200 points, which is generous on purpose: 200 push-ups,
--  100 pull-ups, 400 squats, 800 Russian twists, twenty minutes of plank.
--  Across every week logged so far, only nine person-weeks out of six hundred
--  ever crossed it. Distance cardio carries its own numbers, because a long
--  ride is one session and not a farm: 100 km of running, 100 km of walking,
--  200 km of biking. They live in public.exercises.cap, so tuning one
--  movement is a seed change and never a function change.
--
--  NOTHING IS STAMPED
--  workouts.points stays what the movement is worth. Every board derives the
--  discount on read, which means three things: an edit or a delete can never
--  leave the rows after it mis-scored, the order entries arrived in cannot
--  change a week, and this migration rewrites no history. Lifetime is the sum
--  of its discounted weeks, never one giant pile run through the curve.
--
--  WHAT IT MOVES, ON THE DATA AS IT STANDS
--  The finished week is unchanged in order — its winner still won. In the
--  week in progress two people lose points and everybody else loses none.
--  That is the shape it is meant to have: invisible to anyone training
--  normally, expensive only for concentration.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ------------------------------------------- the budget lives on the bank ---
-- A per-exercise column rather than a constant in a function: the numbers are
-- data, and the one thing worse than an uncapped movement is thinking you
-- capped it in a place nobody looks.
alter table public.exercises
  add column if not exists cap numeric not null default 200;
do $$ begin
  alter table public.exercises add constraint exercises_cap_check check (cap > 0);
exception when duplicate_object then null; end $$;
"""

TAIL = """
commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    parts.append("-- ------------------------------------- the bank, with its caps ---")
    parts.append("-- GENERATED with the rest of the exercise table by")
    parts.append("-- tools/build_exercises.py. Only `cap` is new here.")
    parts.append(open(SEED, encoding="utf-8").read())
    parts.append("-- --------------------------------------- shapes that changed ---")
    parts.append("-- my_stats gained raw_points and cap, and create-or-replace cannot")
    parts.append("-- change what a function returns.")
    for name, args in RESHAPED:
        parts.append("drop function if exists public.%s(%s) cascade;" % (name, args))
    parts.append("")
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
