#!/usr/bin/env python3
"""Write supabase/cup.sql from schema.sql.

A season table rewards consistency, which is the right thing to reward and a
quiet thing to watch: the leader on week 30 is usually the leader on week 31.
The cup is the other half — a straight knockout for the top of the season over
its last four weeks, where one bad week ends you however good the year has
been.

Create-only. Nothing existing changes shape, nothing is dropped, and the
bracket is derived from weekly_history on read, so this rewrites no history and
can be run twice.

Usage:  python3 tools/build_cup_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "cup.sql")

# Order matters: league_cup_state reads cup_seeds, and league_cup reads both.
OBJECTS = ["cup_window", "cup_field", "cup_seed_order", "cup_round_name",
           "cup_seeds", "league_cup_state", "league_cup"]
WANTED = tuple(OBJECTS)

HEAD = """-- ======================================================================
--  IRON LEAGUE — the cup
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED, no points
--  are rewritten, and nothing already live changes shape — this file only
--  adds.
--
--  GENERATED by tools/build_cup_migration.py, which lifts every function below
--  out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  The season table rewards turning up every week. That is the right thing to
--  reward and a quiet thing to watch: by week 30 the top of the table has
--  usually been the top of the table for a month, and the arithmetic says so
--  before the week starts.
--
--  WHAT IT IS
--  A straight knockout for the top of the season, played over its last four
--  weeks, where one bad week ends you however good the year has been.
--
--      · the field is the top 16 of the season — 8 or 4 in a league that
--        cannot fill 16, and no cup at all under 4
--      · the bracket APPEARS ten weeks before the final, drawn from the season
--        table as it stands, so a ninth place can see they would draw the
--        eighth seed and a seventeenth can see exactly what they are missing
--      · it LOCKS four weeks out: whatever the table says then is the draw
--      · then one round a week — round of 16, quarters, semis, final — with
--        the final in the season's last week, so the cup and the table finish
--        together
--
--  A tie is won on the points you score in that league in that week: the same
--  number the weekly board already shows, so there is nothing extra to log and
--  nothing extra to understand. A dead heat goes to the higher seed, which is
--  what keeps the regular season worth playing beyond qualifying.
--
--  WHAT IT DOES NOT DO
--  It pays no season points. Silverware that moved the table would make the
--  last four weeks worth more than the first thirty-four, and the table is the
--  thing that keeps people going.
--
--  NOTHING IS STORED
--  The field, the seeding, every tie and every result are derived from
--  weekly_history on read, the way divisions, streaks, the repetition discount
--  and the season table already are. There is no bracket row to backfill, no
--  result to repair when a week is corrected, and a league that runs this
--  today has an honest cup rather than an invented one.
-- ======================================================================
begin;
set local check_function_bodies = off;
"""

TAIL = """
commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
