#!/usr/bin/env python3
"""Write supabase/season-stats.sql from schema.sql.

The stats tab had two ranges, this week and all time, and a season sat between
them with no way to ask for it. `p_from` bounds the range below, so a season is
"everything since the Monday it opened" — the date league_season_state()
already hands back.

The awkward part is not the SQL, it is the live database. A defaulted third
parameter is meant to keep an app that has not updated working, and it does
NOT: PostgREST resolves a call by argument NAME, and two overloads that both
accept `p_league` and `p_all` are ambiguous, so the old app gets an error
rather than the old answer. The two-argument version therefore has to stop
being visible — and this project's migration channel refuses a DROP, which was
proved by watching `drop function if exists` time out on a function that never
existed. `alter function ... set schema` is not a drop, goes through, and is
reversible, so the old version moves into a `retired` schema that PostgREST
does not look in. Same transaction, so there is never a moment where both are
callable.

Usage:  python3 tools/build_stats_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "season-stats.sql")

OBJECTS = ["my_stats", "my_muscles"]
WANTED = ("my_stats", "my_muscles")

# The two-argument shapes that have to stop being visible, with the identity
# arguments Postgres prints for them — matched exactly, so a database that has
# already been migrated skips the move instead of failing.
RETIRED = [
    ("my_stats", "p_league uuid, p_all boolean"),
    ("my_muscles", "p_league uuid, p_all boolean"),
]

HEAD = """-- ======================================================================
--  IRON LEAGUE — a season range on the stats tab
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED and no points
--  are rewritten.
--
--  GENERATED by tools/build_stats_migration.py, which lifts both functions
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  The stats tab offered THIS WEEK and ALL TIME. A season is the unit the
--  league actually plays in, and it had no tab — so "how is my season going"
--  could only be answered by the hall of fame table, which shows placings,
--  not what you lifted.
--
--  WHAT CHANGES
--  my_stats() and my_muscles() take a third argument, `p_from`, which bounds
--  the range below. null is the behaviour they already had.
--
--      week    p_all false, p_from null    this week, as before
--      season  p_all true,  p_from <date>  since the Monday the season opened
--      all     p_all true,  p_from null    the lot, as before
--
--  The date comes from league_season_state().first_week, so an off-season
--  shows the season that just closed rather than an empty tab.
--
--  THE PART THAT IS NOT OBVIOUS
--  A defaulted third parameter looks like it keeps an app that has not updated
--  working. It does not. PostgREST resolves a call by argument NAME, and both
--  the two-argument and the three-argument version accept `p_league` and
--  `p_all`, so an old app's call matches both and Postgres refuses it:
--
--      function public.my_stats(p_league => ..., p_all => ...) is not unique
--
--  So exactly one of them may be visible. This file moves the two-argument
--  version into a `retired` schema instead of dropping it: PostgREST does not
--  look there, the move is reversible, and — unlike a drop — the migration
--  channel this project applies through will actually run it. Both happen in
--  one transaction, so there is no instant where both are callable and no
--  instant where neither is.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ------------------------------------------------- somewhere to put it ---
-- Not exposed to PostgREST and no rights for anybody, so what lands here is
-- unreachable from an app while staying recoverable with one more ALTER.
create schema if not exists retired;
revoke all on schema retired from public;
"""

TAIL = """
commit;
"""

MOVE = """-- ------------------------------------------- and the old shapes, retired ---
do $mv$
declare r record; alias text;
begin
  for r in
    select p.oid as id, p.oid::regprocedure as sig, p.proname as nom
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and (p.proname, pg_get_function_identity_arguments(p.oid)) in (%s)
  loop
    begin
      execute format('alter function %%s set schema retired', r.sig);
    exception when duplicate_function then
      -- An older generated migration re-created the shape this file retires and
      -- a copy is already parked, so the obvious name is taken. Park this one
      -- under its own rather than leave it visible: a visible twin is what
      -- makes every call from an app that has not updated ambiguous.
      alias := r.nom || '_' || r.id::text;
      execute format('alter function %%s rename to %%I', r.sig, alias);
      execute format('alter function public.%%I(%%s) set schema retired',
                     alias, pg_get_function_identity_arguments(r.id));
    end;
    raise notice 'retired %%', r.sig;
  end loop;
end $mv$;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    pairs = ",\n           ".join("('%s', '%s')" % (n, a) for n, a in RETIRED)
    parts.append(MOVE % pairs)
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
