#!/usr/bin/env python3
"""Write supabase/progressions.sql from the regenerated exercise seed.

Thirty-three exercises, and not one line of scoring code changes: the bank is
data, so adding to it is an insert. The reason for the batch is that the
league was only paying for the top of every skill ladder — you could log a
front lever but not the tuck you spend three months on, an L-sit but not the
tucked one, a pistol but not the box pistol on the way to it.

The rates are set so that AN HONEST SET AT YOUR OWN LEVEL is worth about the
same at every rung: twenty seconds of crow pays 4, twenty seconds of a
freestanding handstand pays 10, five seconds of a full planche pays 5. The
rate climbs steeply with difficulty and the hold you can actually finish
shrinks just as fast, so the two cancel. That is the point — the ladder is
there to be climbed, not to pay whoever is already at the top of it.

Usage:  python3 tools/build_progression_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

SEED = os.path.join(ROOT, "tools", "exercises.sql")
OUT = os.path.join(ROOT, "supabase", "progressions.sql")

HEAD = """-- ======================================================================
--  IRON LEAGUE — the rungs, not just the top of the ladder
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. NOTHING LOGGED CHANGES and no scoring code moves —
--  the exercise bank is data, so adding to it is an insert.
--
--  GENERATED by tools/build_progression_migration.py from the seed that
--  tools/build_exercises.py writes. Edit tools/exercise_bank.py, re-run both,
--  never edit this file.
--
--  WHAT IS NEW  (33 exercises, 131 -> 164)
--
--  Handstand line   crow / frog stand, headstand, wall handstand,
--                   forearm stand (pincha), freestanding handstand
--  Planche line     tuck, straddle, full
--  L-sit line       tucked L-sit, one-leg L-sit, V-sit
--  Front lever      tuck, advanced tuck, straddle
--  Back lever       tuck, full
--  Flag             chamber / tuck flag, human flag
--  Pull-up line     jumping pull-up, negative pull-up
--  Push-up line     dive bomber, elevated pike, wall walk
--  Squat line       cossack, box pistol, archer squat
--  Core             hollow rocks, windshield wipers, full bridge
--  Grip             one-arm hang, loaded carry
--  Loaded cardio    weighted run (6.5/km), rucking (3.5/km)
--
--  HOW THEY ARE PRICED
--  A skill hold is priced per hour of hold, like every other hold in the app.
--  The rates rise steeply with difficulty, and the hold a person can actually
--  finish shrinks just as fast, so a real set at any rung is worth about the
--  same:
--
--      20 s crow                (a first balance)        4.0 pts
--      20 s tucked L-sit                                 5.0
--      30 s wall handstand                               7.5
--      20 s tuck front lever                             6.7
--      20 s freestanding handstand                      10.0
--      10 s straddle front lever                         6.0
--       5 s full planche        (a handful of people)    5.0
--
--  Nobody is punished for standing at the bottom of a ladder and nobody is
--  paid twice for standing at the top. The same holds for the rep lines: a
--  jumping pull-up is 1.0 against a pull-up's 2.0, a box pistol 0.75 against
--  a pistol's 2.0 — worth logging, never worth more than the real thing.
--
--  The two loaded-cardio entries carry their own weekly budget, like run and
--  walk do: 650 for a weighted run and 350 for rucking, both of which are
--  100 km at their own rate.
-- ======================================================================
begin;
"""

TAIL = """
commit;
"""


def main():
    parts = [HEAD]
    parts.append("-- ------------------------------------- the bank, with the new rungs ---")
    parts.append("-- GENERATED by tools/build_exercises.py. Existing rows are refreshed")
    parts.append("-- with identical values; the 33 new ones are inserted.")
    parts.append(open(SEED, encoding="utf-8").read())
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
