#!/usr/bin/env python3
"""Write supabase/gym-lifts.sql from schema.sql.

Three things, and only the first one changes a number anybody has already
been given — which it does not, because points are stamped when a row is
written, so no logged workout moves.

  1. R = own + load x equip / bodyweight. `own` is the part of the bodyweight
     fraction a lift already carries. It was a boolean (0.85 for a standing
     leg lift, nothing for everything else), which made a weighted dip or a
     weighted pull-up score a THIRD of the same rep with an empty belt.
  2. Thirteen gym lifts, including the first two that lead with forearms and
     lower back — regions a gym-only member simply could not fill.
  3. The bar hint, which said "the total on the bar" and was being read as
     "the plates on the bar".

Usage:  python3 tools/build_gym_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
SEED = os.path.join(ROOT, "tools", "exercises.sql")
OUT = os.path.join(ROOT, "supabase", "gym-lifts.sql")

OBJECTS = ["calc_points"]
WANTED = ("calc_points",)

HEAD = """-- ======================================================================
--  IRON LEAGUE — the gym formula, and the rest of the gym
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. NO LOGGED WORKOUT CHANGES: points are stamped when a
--  row is written, so this prices what comes next and rewrites nothing.
--
--  GENERATED by tools/build_gym_migration.py, which lifts calc_points() out
--  of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHAT WAS WRONG
--  A gym lift is priced by the fraction of bodyweight it moves, the same
--  quantity that prices a push-up. How much of the lifter's own body the
--  movement already carries was a yes/no: 0.85 for a standing leg lift and
--  nothing for everything else. That is right for a bench and wrong for
--  anything you hang from, because the number typed into a weighted dip is
--  what is on the BELT. So, for a 70 kg lifter:
--
--      Weighted Dips      20 kg on the belt   0.45 /rep
--      Dips               no belt at all      1.50 /rep
--      Weighted Pull-up   20 kg on the belt   0.57 /rep
--      Pull-ups           no belt at all      2.00 /rep
--
--  Adding weight made the movement worth less, and you needed 67 kg round
--  your waist before a weighted dip caught up with a plain one.
--
--  WHAT IT IS NOW
--      R = own + (load x equip) / bodyweight
--
--  `own` is that fraction written properly. The belt lifts take theirs from
--  the anchors, so a weighted dip with an empty belt scores EXACTLY what a
--  dip scores and there is no cheaper way to log the same rep:
--
--      Weighted Dips      0 / 10 / 20 / 40 kg   1.50  1.72  1.95  2.39
--      Weighted Pull-up                         2.00  2.29  2.57  3.14
--      Weighted Calf Raise                      0.20  0.26  0.33  0.45
--
--  A standing leg lift keeps the 0.85 it always had — a 60 kg back squat at
--  70 kg bodyweight is 1.00 a rep, exactly as before. A bench is unchanged
--  too: at 70 kg bodyweight it takes 45 kg to match your own push-up, which
--  is 0.64 x 70, which is the whole point of the model.
--
--  THIRTEEN NEW LIFTS
--  Chest fly, machine shoulder press, skullcrusher, preacher curl, hammer
--  curl, rear delt fly, T-bar row, trap bar deadlift, upright row, wrist
--  curl, hack squat, hip abduction, back extension.
--
--  Two of the fourteen regions on the figure had NO gym lift that led with
--  them — forearms and lower back — so a gym-only member could not fill them
--  however hard they trained. The wrist curl and the back extension close
--  both. The back extension is also the first gym entry worth points with no
--  plate held at all: it lands beside supermans.
-- ======================================================================
begin;
set local check_function_bodies = off;
"""

TAIL = """
commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    parts.append("-- ------------------------------- the bank, with `own` and the new lifts ---")
    parts.append("-- GENERATED with the rest of the exercise table by")
    parts.append("-- tools/build_exercises.py. Every gym mode now carries `own`.")
    parts.append(open(SEED, encoding="utf-8").read())
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
