#!/usr/bin/env python3
"""Write supabase/season-table.sql from schema.sql.

People start and fade. A week is a sprint and winning it is all-or-nothing, so
anybody who cannot realistically top the board has no reason to care by
Wednesday — and the "first to five crowns" race this replaces had exactly the
same hole, because only a winner ever moved.

Every finished week now pays by FINISHING POSITION and the season adds it up.
Nothing is stored: the table is derived from weekly_history on read, the way
divisions, streaks and the repetition discount already are, so this migration
rewrites no history and can be run twice.

Usage:  python3 tools/build_season_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "season-table.sql")

# my_badges loses three rows, which does not change its shape, so it is a
# plain replace. Nothing else here existed before.
OBJECTS = ["rank_points", "league_week0", "season_index",
           "league_season_info", "league_season", "my_badges"]

WANTED = ("rank_points", "league_week0", "season_index",
          "league_season_info", "league_season", "my_badges")

HEAD = """-- ======================================================================
--  IRON LEAGUE — a season table instead of a race to five crowns
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. NOTHING LOGGED IS TOUCHED and no points are rewritten.
--
--  GENERATED by tools/build_season_migration.py, which lifts every function
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  WHY
--  People start and then fade. A week is a sprint and winning it is
--  all-or-nothing, so anybody who cannot realistically top the board has no
--  reason to care by Wednesday. The crowns race had the same hole: only a
--  winner ever moved, so "first to five" was a contest between the same two
--  or three people and wallpaper for everybody else.
--
--  WHAT CHANGES
--  Every finished week now pays out by FINISHING POSITION, the way a motor
--  racing season does, and the season adds it up:
--
--      1st  5.00     6th  1.60     11th 0.70     16th 0.27
--      2nd  3.60     7th  1.35     12th 0.60     17th 0.21
--      3rd  2.80     8th  1.15     13th 0.50     18th 0.16
--      4th  2.30     9th  1.00     14th 0.40     19th 0.13
--      5th  1.90    10th  0.85     15th 0.33     20th 0.10
--
--  21st and below score nothing, which is the one rung that has to hurt.
--
--  The shape is deliberate. A win is worth 39% more than second — the same
--  gap motor racing uses — so the top of the board still means something.
--  Below that it decays gently enough that climbing always pays: 16th to 11th
--  more than doubles your week, and tenth is a fifth of a win rather than a
--  rounding error. Over 38 weeks a perfect run is 190 and a steady tenth is
--  32: far apart, and both of them are a season.
--
--  THE SEASON
--  leagues.season_weeks already existed and did nothing but print itself. It
--  is the season length now, and its ceiling goes from 26 to 52 so a real
--  season fits — 38 for a football year, 50 for a calendar one. null is one
--  open season that never ends.
--
--  A season is counted in CALENDAR weeks from the Monday the league was
--  created, not in weeks that happened to have activity. A quiet week still
--  burns a week of the season; otherwise a league that goes dead for a month
--  would quietly extend its own season and the table would never close.
--
--  Weeks already played are in season 1 — there is nothing to backfill,
--  because the table is derived from weekly_history on read rather than
--  stored. Crowns still follow the person across every season.
--
--  WHAT GOES
--  The TRIPLE CROWN, FIVE CROWNS and TEN CROWNS badges. CHAMPION — win a
--  week — stays, because winning a week is still the thing.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ----------------------------------------- a real season has to fit ---
-- 26 weeks was the ceiling from when this column was a label and nothing read
-- it. A football season is 38 and a long one is 50.
alter table public.leagues drop constraint if exists leagues_season_sane;
alter table public.leagues add constraint leagues_season_sane
  check (season_weeks is null or season_weeks between 1 and 52);

-- A new league gets a football season unless its owner says otherwise. An
-- open-ended season has no finish line to play for, which is the whole point
-- of the table. Existing leagues keep whatever they already have.
alter table public.leagues alter column season_weeks set default 38;
"""

TAIL = """
commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
