#!/usr/bin/env python3
"""Write supabase/membership.sql from schema.sql.

Two halves of the same thing: somebody leaving a league, and the control room
taking them out of one. They have to agree about the awkward cases, so they
share drop_membership() — and the awkward cases are the point of the file.

THE LEAGUE IS NEVER DELETED when the last member leaves. Deleting it cascades
its workouts away, and a workout is what a lifetime total is made of: somebody
who leaves their only league to keep a quiet account would come back to a rank
of nothing.

leave_league() already exists and changes body only, so create-or-replace is
enough and nothing has to be dropped.

Usage:  python3 tools/build_membership_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "membership.sql")

OBJECTS = ["drop_membership", "leave_league", "admin_memberships",
           "admin_remove_member"]
WANTED = tuple(OBJECTS)

HEAD = """-- ======================================================================
--  IRON LEAGUE — leaving a league, and being taken out of one
--
--  Paste the whole file into the Supabase SQL editor and press RUN, or apply
--  it over the API. Safe to run twice. NOTHING LOGGED IS TOUCHED and no
--  points are rewritten.
--
--  GENERATED by tools/build_membership_migration.py, which lifts every
--  function below out of supabase/schema.sql. Edit there and re-run it,
--  never here.
--
--  WHAT CHANGES
--  · leave_league() now goes through drop_membership(), which handles the two
--    cases the old one-line delete did not.
--  · admin_memberships() lists who is in what, for the control room.
--  · admin_remove_member() takes one person out of one league. The account,
--    its restore code, its badges and everything it logged anywhere else are
--    untouched — this is the half of admin_delete_profile() that somebody
--    usually actually wants.
--
--  THE LEAGUE IS NEVER DELETED, even when the last member walks out.
--  leagues.id is the parent of workouts.league_id ON DELETE CASCADE, and a
--  workout is what a lifetime total is made of. Somebody who leaves their
--  only league to keep a quiet account must come back to the rank they
--  earned, not to zero. An empty league is invisible to everybody — my_leagues
--  only returns what you are a member of — and costs one row; the control room
--  can delete it when it really is rubbish.
--
--  IF THE OWNER LEAVES, the league goes to whoever has been in it longest, so
--  the settings and the crest never end up unreachable. If the owner was the
--  last one out they stay the owner of an empty league, which means rejoining
--  with the code hands it straight back.
-- ======================================================================
begin;
set local check_function_bodies = off;
"""

TAIL = """
commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
