#!/usr/bin/env python3
"""Turn the licensed anatomy into the figure app.js draws, and splice it in.

The art is not ours and is not drawn here. `tools/body_source.json` holds the
SVG paths of four bodies — male and female, front and back — taken from
react-native-body-highlighter, MIT licensed, (c) 2022 ELABBASSI Hicham. See
vendor/body/ for the licence and why this replaced a hand-drawn figure.

What IS ours is the mapping: which of that illustration's parts answer to each
of the fourteen regions the app scores. Keeping that here means the art can be
swapped for better art without touching a single muscle share.

Usage:  python3 tools/build_body.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from exercise_bank import MUSCLE_ORDER, MUSCLE_VIEW                # noqa: E402

SOURCE = os.path.join(HERE, "body_source.json")

# The illustration draws the back body offset to the right in the same
# coordinate space, so each view is a window onto one canvas.
BOX = {'front': '0 0 724 1448', 'back': '724 0 724 1448'}

# Their part -> our region. Everything on the left is a name in the source art;
# everything on the right is a key the app scores.
REGION = {
    'chest': 'chest',
    'deltoids': 'shoulders',
    'biceps': 'biceps',
    'triceps': 'triceps',
    'forearm': 'forearms',
    'trapezius': 'traps',
    'upper-back': 'lats',
    'lower-back': 'lowerback',
    'abs': 'abs',
    'obliques': 'obliques',
    'gluteal': 'glutes',
    'quadriceps': 'quads',
    'hamstring': 'hamstrings',
    'calves': 'calves',
}

# Parts of the body that are not regions the app tracks. They are drawn, in the
# body's own colour and deaf to taps, because a figure with no head is not a
# figure. The tibialis is here on purpose: it is the shin, not the calf, and
# lighting it up for a set of calf raises would be a small lie told fourteen
# times a week.
INERT = {'head', 'hair', 'neck', 'hands', 'feet', 'ankles', 'knees',
         'adductors', 'tibialis'}

# Two figures, because the art has two. Anyone still stored as 'neutral' — the
# default before this — is drawn as the male one until they choose.
FORMS = {'masc': 'male', 'fem': 'female'}


def main():
    src = json.load(open(SOURCE, encoding="utf-8"))

    unknown = {g['slug'] for b in src.values() for g in b} - set(REGION) - INERT
    assert not unknown, 'the art has parts nothing accounts for: %s' % sorted(unknown)

    body = {}
    for form, who in FORMS.items():
        body[form] = {'box': {}, 'front': [], 'back': [], 'inert': {}}
        for view in ('front', 'back'):
            groups = src['%s_%s' % (who, view)]
            body[form]['box'][view] = BOX[view]
            body[form]['inert'][view] = [
                d for g in groups if g['slug'] in INERT for d in g['paths']]
            body[form][view] = [
                {'m': REGION[g['slug']], 'd': d}
                for g in groups if g['slug'] in REGION for d in g['paths']]

    # Every region the app scores has to exist on the side it claims, or a
    # number in the list points at nothing on the figure.
    for form, v in body.items():
        for view in ('front', 'back'):
            drawn = {p['m'] for p in v[view]}
            want = {m for m in MUSCLE_ORDER if MUSCLE_VIEW[m] in (view, 'both')}
            missing = want - drawn
            assert not missing, (form, view, 'not in the art: %s' % sorted(missing))
            extra = drawn - want
            assert not extra, (form, view, 'drawn but not claimed: %s' % sorted(extra))

    js = ('  /* BODY BEGIN */\n'
          '  /* GENERATED by tools/build_body.py — do not edit by hand.\n'
          '     The anatomy is SVG path data from react-native-body-highlighter,\n'
          '     MIT licensed, (c) 2022 ELABBASSI Hicham. Licence and reasoning in\n'
          '     vendor/body/. `m` is the region a path answers to; `inert` is the\n'
          '     rest of the body, drawn but not scored and deaf to taps. */\n'
          '  var BODY = ' + json.dumps(body, separators=(',', ':')) + ';\n'
          + '  /* BODY END */')

    app = os.path.join(ROOT, 'app.js')
    text = open(app, encoding='utf-8').read()
    a = text.index('  /* BODY BEGIN */')
    b = text.index('/* BODY END */', a) + len('/* BODY END */')
    out = text[:a] + js + text[b:]
    if out != text:
        open(app, 'w', encoding='utf-8').write(out)
        print('spliced app.js')
    else:
        print('app.js already up to date')
    for form in FORMS:
        print('  %-8s front %d paths + %d inert · back %d + %d'
              % (form, len(body[form]['front']), len(body[form]['inert']['front']),
                 len(body[form]['back']), len(body[form]['inert']['back'])))


if __name__ == '__main__':
    main()
