#!/usr/bin/env python3
"""Write supabase/catch-up-day.sql from schema.sql.

Every function in the migration is lifted out of schema.sql rather than
retyped. The two whose shape changed are dropped first, because
`create or replace` cannot change what a function returns.

Usage:  python3 tools/build_catchup.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "catch-up-day.sql")

RESHAPED = [
    ("my_leagues", ""),
    ("set_league_settings", "uuid, int[], int"),
]

OBJECTS = ["catchup_floor", "catchup_ceiling", "catchup_max",
           "is_catchup_day", "catchup_multiplier",
           "workouts_stamp", "set_league_settings", "my_leagues"]

WANTED = ("is_catchup_day", "catchup_multiplier", "catchup_floor",
          "catchup_ceiling", "catchup_max", "set_league_settings")

HEAD = """-- ======================================================================
--  IRON LEAGUE — the catch-up day, and five more places in a league
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_catchup.py, which lifts every function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  THE CATCH-UP DAY
--  One day a week, chosen per league, where being behind is worth something.
--  Everything logged that day is multiplied by how far off the lead you were
--  at the moment you logged it:
--
--      under 150 behind   x1.00
--      200                x1.06
--      300                x1.17
--      400                x1.29
--      500 or more        x1.40
--
--  It is not a handicap. The leader still trains and still scores every
--  point they earn; they simply score at x1.00 like anybody within touching
--  distance. Nobody loses anything, ever, and the most it can be worth is
--  forty per cent. It exists so somebody who missed four days has a reason
--  to turn up on Sunday instead of writing the week off.
--
--  The multiplier is stamped on the row as it is written, so it never
--  changes afterwards: two people logging the same set an hour apart can
--  legitimately score differently, and both keep what they earned.
--
--  A league starts with no catch-up day at all. It cannot be a rest day.
--
--  SIX MORE PLACES
--  A league holds 36 instead of 30, and the leagues that already exist are
--  widened to match. 36 rather than a round number because the five
--  divisions come to exactly that, and an even league is what lets the
--  Monday rivalry pair everybody off without leaving one person out.
-- ======================================================================
begin;

-- ------------------------------------------------------- the new columns ---
alter table public.leagues
  add column if not exists catchup_dow int;
do $$ begin
  alter table public.leagues add constraint leagues_catchup_sane
    check (catchup_dow is null or catchup_dow between 1 and 7);
exception when duplicate_object then null;
end $$;

alter table public.workouts
  add column if not exists boost numeric not null default 1;
do $$ begin
  alter table public.workouts add constraint workouts_boost_check
    check (boost between 1 and 3);
exception when duplicate_object then null;
end $$;

-- ----------------------------------------------------- six more places -----
alter table public.leagues drop constraint if exists leagues_max_members_check;
update public.leagues set max_members = 36 where max_members in (30, 35);
alter table public.leagues
  add constraint leagues_max_members_check check (max_members between 2 and 36);

"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    parts.append("-- ---------------------------------------------- shapes that changed ---")
    parts.append("-- create-or-replace cannot change what a function returns, and it cannot")
    parts.append("-- add a parameter either, so these two go first and are rebuilt below.")
    for name, args in RESHAPED:
        parts.append("drop function if exists public.%s(%s) cascade;" % (name, args))
    parts.append("")
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- the stamp trigger is recreated with the function it calls")
    parts.append("""drop trigger if exists workouts_stamp_trg on public.workouts;
create trigger workouts_stamp_trg
  before insert on public.workouts
  for each row execute function public.workouts_stamp();
""")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append("\ncommit;")
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
