#!/usr/bin/env python3
"""Write supabase/body-and-crowns.sql from schema.sql.

Three things at once, because they arrived together and a database that has
one of them and not the others is a state nobody should have to reason about:
the muscle figure, the crowns tracker, and the repriced holds and cardio.

The rates need a word. Points are stamped on a row when it is written, so
changing a rate never rewrites history — which is right, and also means the
week in progress would end up half-priced at the old rates and half at the
new ones. So the migration rescores THIS WEEK and only this week, from the
amounts and bodyweights already on the rows, keeping each row's catch-up
multiplier. Finished weeks are left exactly as they were.

Usage:  python3 tools/build_body_migration.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
SEED = os.path.join(ROOT, "tools", "exercises.sql")
OUT = os.path.join(ROOT, "supabase", "body-and-crowns.sql")

RESHAPED = [
    ("weekly_history", "uuid"),
    ("my_badges", "uuid"),
]

# weekly_history is dropped and rebuilt, and two of these read it, so it goes
# back first. check_function_bodies is off as well, for the same reason
# schema.sql turns it off: these functions reference each other and Postgres
# resolves a SQL body at create time, so a strict run stops at the first
# forward reference whatever order they are in.
OBJECTS = ["weekly_history", "muscle_charge", "muscle_dose", "my_muscles",
           "league_wins",
           "league_champions", "set_body_form", "my_badges", "workouts_update_guard"]

WANTED = ("muscle_charge", "muscle_dose", "my_muscles", "league_wins",
          "league_champions",
          "set_body_form", "weekly_history", "my_badges", "public.muscles")

HEAD = """-- ======================================================================
--  IRON LEAGUE — the muscle figure, the crowns, and a fairer points table
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. No finished week is touched or rewritten.
--
--  GENERATED by tools/build_body_migration.py, which lifts every function
--  below out of supabase/schema.sql. Edit there and re-run it, never here.
--
--  THE FIGURE
--  Every exercise now says what it trains, as a share of the points it
--  scores: a hundred points of bench press put fifty into the chest and
--  thirty into the triceps. Fourteen regions, drawn on a front and a back.
--
--  A region's reading is not its share of your work — that would make
--  training your legs harder make your chest look worse, and it would say
--  nothing about whether you did enough. Each one is measured against a full
--  week's dose of itself instead:
--
--      pct = 100 x points / target
--
--  100% is a week of that muscle done. There are fourteen of them and your
--  score is the one you have filled least, so the way up is always the thing
--  you have been avoiding. Over a range longer than a week the target grows
--  with the weeks actually trained, so the all-time figure keeps meaning
--  something in month three.
--
--  THE CROWNS
--  One per week won, counted from the finished weeks the Hall of Fame is
--  already built from. Nothing is stored and nothing is backfilled, so a
--  league that starts today starts empty and honestly.
--
--  While fixing that: a finished week used to be recorded with its combo
--  bonus but without its bounty, so a week won on a Thursday quest could go
--  in the books as a week lost. Both are counted now, and a tie is broken
--  the way the live board breaks it.
--
--  THE RATES
--  Two families were priced wrong against everything else:
--
--    holds     A plank paid 2 points a minute and a dead hang 1 point per
--              30 seconds, while a set of reps pays 20-30 a minute. Thirty
--              seconds of plank was worth one point. Endurance holds now pay
--              what a hard set pays; the skill holds keep their premium.
--
--    cardio    An hour of running paid 50, an hour of swimming 12, an hour
--              of rowing 10 and an hour of skipping 8. The continuous ones
--              now sit at 30-33 an hour: below running, because a duration
--              is not a distance, but inside the same argument. Team and
--              racket sports go from 10 and 7 an hour to 18 and 12 — still
--              the cheapest hour there is.
--
--  Nothing anybody has already earned changes. Points are stamped when a row
--  is written, so every finished week keeps its numbers exactly. The week in
--  progress is rescored at the end of this file so it is not half old and
--  half new — from the amounts already on the rows, keeping each row's
--  catch-up multiplier.
--
--  ONE MORE THING
--  Editing an entry used to rescore it without its catch-up multiplier, so
--  fixing a typo in a set logged on a catch-up day quietly took forty per
--  cent off it. The multiplier belongs to the moment the set was logged and
--  now rides through an edit. Nothing is repaired retroactively; it simply
--  stops happening.
-- ======================================================================
begin;
set local check_function_bodies = off;

-- ---------------------------------------------------- the new columns ---
alter table public.exercises
  add column if not exists muscles jsonb not null default '{}'::jsonb;

alter table public.profiles
  add column if not exists body_form text not null default 'neutral';
do $$ begin
  alter table public.profiles add constraint profiles_body_form_check
    check (body_form in ('masc','fem','neutral'));
exception when duplicate_object then null;
end $$;

-- The rescore at the bottom multiplies by each row's catch-up multiplier, so
-- the column has to be there. It will be on any database that has run
-- catch-up-day.sql; this is here so the file does not half-apply on one that
-- has not.
alter table public.workouts
  add column if not exists boost numeric not null default 1;

create table if not exists public.muscles (
  key    text primary key,
  name   text not null,
  view   text not null check (view in ('front','back','both')),
  target int  not null check (target > 0),
  sort   int  not null default 0
);
alter table public.muscles enable row level security;
drop policy if exists muscles_read on public.muscles;
create policy muscles_read on public.muscles
  for select to authenticated using (true);

"""

TAIL = """
-- ------------------------------------------- the week in progress only ---
-- Rescore what is running so a single week is not priced two ways. The
-- amounts, bodyweights and loads are already on the rows, and each row keeps
-- the catch-up multiplier it was logged at, so this reproduces exactly what
-- the trigger would have written today. Finished weeks are not in scope and
-- are never touched.
update public.workouts w
   set points = round(
         public.calc_points(w.exercise_key, w.mode, w.amount, w.bodyweight, w.load)
         * w.boost, 2)
 where w.week_start = public.current_week_start()
   and round(public.calc_points(w.exercise_key, w.mode, w.amount,
                                w.bodyweight, w.load) * w.boost, 2) is distinct from w.points;

commit;
"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]
    parts.append("-- ----------------------------------- the bank, with its muscles ---")
    parts.append("-- GENERATED with the rest of the exercise table by")
    parts.append("-- tools/build_exercises.py; the new rates are in here too.")
    parts.append(open(SEED, encoding="utf-8").read())
    parts.append("-- ---------------------------------------------- shapes that changed ---")
    parts.append("-- create-or-replace cannot change what a function returns, so the two")
    parts.append("-- that gained a column go first and are rebuilt below.")
    for name, args in RESHAPED:
        parts.append("drop function if exists public.%s(%s) cascade;" % (name, args))
    parts.append("")
    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")
    parts.append("-- the edit guard is recreated with the function it calls")
    parts.append("""drop trigger if exists workouts_update_guard_trg on public.workouts;
create trigger workouts_update_guard_trg
  before update on public.workouts
  for each row execute function public.workouts_update_guard();
""")
    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append(TAIL)
    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
