#!/usr/bin/env python3
"""Write supabase/scoring-modes.sql from schema.sql.

Every function in the migration is lifted out of schema.sql rather than
retyped. The two functions whose shape changed are dropped first, because
`create or replace` cannot change what a function returns.

Usage:  python3 tools/build_scoring.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from sqllift import lift, grants                                   # noqa: E402

SCHEMA = os.path.join(ROOT, "supabase", "schema.sql")
OUT = os.path.join(ROOT, "supabase", "scoring-modes.sql")

# create-or-replace cannot change a function's return type, so these two are
# dropped first. Nothing depends on them but other functions, and Postgres
# does not track function-to-function dependencies, so nothing else goes.
RESHAPED = [
    ("league_leaderboard", "uuid, date"),
    ("my_leagues", ""),
]

OBJECTS = [
    "decay_full", "decay_half", "decay_points", "week_base_points",
    "league_leaderboard", "weekly_history", "my_leagues",
    "set_league_scoring",
]

WANTED = ("decay_full", "decay_half", "decay_points", "week_base_points",
          "set_league_scoring")

HEAD = """-- ======================================================================
--  IRON LEAGUE — how a league scores
--
--  Paste the whole file into the Supabase SQL editor and press RUN.
--  Safe to run twice. Nothing anybody has logged is touched or rewritten.
--
--  GENERATED by tools/build_scoring.py, which lifts every function below out
--  of supabase/schema.sql. Edit there and re-run it — never this file.
--
--  Every league keeps scoring exactly as it does today. The column defaults
--  to 'hardcore', which is the behaviour that has always existed, so nothing
--  changes for anyone until somebody chooses otherwise for their own league.
--
--  HARDCORE   every rep counts the same, however many you do. Raw volume,
--             raw competition. This is what every league is now.
--
--  BALANCED   the first 40 points from ONE exercise on ONE day count in
--             full, 40 to 85 at 70%, past 85 at 40%. Time and distance work
--             gets twice the allowance, because you cannot farm a marathon.
--             Recovery is never tapered.
--
--             A fifteen-minute session loses about 3%. Three hours grinding
--             one movement loses about half. Varying the same effort across
--             two exercises is worth roughly a third more than putting it
--             all into one.
--
--  The taper reads base points only. Bounties, the daily combo and raids are
--  untouched, so the flat rewards a busy person can actually reach are worth
--  relatively more in a balanced league — which is the point.
-- ======================================================================
begin;

-- ------------------------------------------------------------ the column ---
alter table public.leagues
  add column if not exists scoring text not null default 'hardcore';

do $$ begin
  alter table public.leagues add constraint leagues_scoring_known
    check (scoring in ('hardcore', 'balanced'));
exception when duplicate_object then null;
end $$;

"""


def main():
    schema = open(SCHEMA, encoding="utf-8").read()
    parts = [HEAD]

    parts.append("-- ---------------------------------------------- shapes that changed ---")
    parts.append("-- create-or-replace cannot change what a function returns, so these go")
    parts.append("-- first and are rebuilt below.")
    for name, args in RESHAPED:
        parts.append("drop function if exists public.%s(%s) cascade;" % (name, args))
    parts.append("")

    for name in OBJECTS:
        parts.append("-- " + ("-" * (70 - len(name))) + " " + name + " ---")
        parts.append(lift(schema, "function", name) + "\n")

    parts.append("-- -------------------------------------------------------- grants ---")
    parts.append(grants(schema, WANTED))
    parts.append("\ncommit;")

    body = "\n".join(parts) + "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(body.splitlines())))


if __name__ == "__main__":
    main()
