// Generated by tools/build_ios_icons.py — do not edit.
//
// The same four icon sets the web app uses, in the same order, so a choice
// made on either side means the same thing. Keeping this generated is what
// stops the two apps drifting apart.

enum IconSet {

    /// What a person can wear as their mark — 72 of them.
    static let avatars: [String] = [
        "wolf-head", "lion", "tiger-head", "bear-head",
        "gorilla", "boar-tusks", "bull", "horse-head",
        "elephant", "rhinoceros-horn", "cobra", "snake",
        "scorpion", "shark-bite", "octopus", "t-rex-skull",
        "triceratops-head", "raven", "owl", "eagle-head",
        "fox", "panda", "cat", "croc-jaws",
        "spartan-helmet", "viking-helmet", "samurai-helmet", "centurion-helmet",
        "crested-helmet", "dwarf-helmet", "knight-banner", "skull-crack",
        "flame", "lightning-storm", "crossed-swords", "battle-axe",
        "war-axe", "hammer-drop", "trident", "bowman",
        "crossbow", "ninja-head", "barbarian", "pirate-captain",
        "robot-golem", "cyborg-face", "alien-skull", "grim-reaper",
        "ghost", "overlord-helm", "dragon-head", "hydra",
        "minotaur", "kraken-tentacle", "mountains", "anvil-impact",
        "broadsword", "shield-bash", "sword-spade", "muscle-up",
        "biceps", "weight-lifting-up", "boot-stomp", "punch",
        "punch-blast", "fist", "bull-horns", "star-formation",
        "sun", "crescent-blade", "running-ninja", "rune-sword",
    ]

    /// What a league can wear as its crest — 56, and never a face, so a crest can never be mistaken for a player.
    static let crests: [String] = [
        "heraldic-sun", "triquetra", "fleur-de-lys", "camargue-cross",
        "cross-flare", "allied-star", "barbed-star", "beveled-star",
        "falling-star", "triple-gate", "castle", "guarded-tower",
        "radio-tower", "anchor", "compass", "big-gear",
        "gears", "cog", "battle-gear", "chess-king",
        "chess-knight", "chess-rook", "chess-bishop", "archery-target",
        "on-target", "arrow-cluster", "arrowhead", "angel-wings",
        "batwing-emblem", "feathered-wing", "two-feathers", "holy-oak",
        "oak-leaf", "ginkgo-leaf", "leaf-swirl", "heavy-lightning",
        "chain-lightning", "lightning-arc", "thunderball", "mountaintop",
        "rune-stone", "spiral-bloom", "divided-spiral", "abstract-001",
        "abstract-013", "abstract-024", "abstract-034", "abstract-050",
        "crenulated-shield", "bordered-shield", "checked-shield", "edged-shield",
        "laurel-crown", "royal-love", "tribal-pendant", "maze-cornea",
    ]

    /// Badge artwork, keyed by the badge the server hands out.
    static let badgeArt: [String: String] = [
        "week_win": "podium-winner",
        "week_second": "podium-second",
        "week_third": "podium-third",
        "improved": "progression",
        "apex": "summits",
        "streak7": "sands-of-time",
        "streak14": "hourglass",
        "streak30": "time-trap",
        "bounty_first": "wax-seal",
        "bounty5": "ribbon-medal",
        "duel3": "medal",
        "duel10": "medallist",
        "combo5": "lightning-trio",
        "century": "muscular-torso",
        "grand": "diamond-hard",
        "earlybird": "spark-spirit",
        "nightowl": "eclipse-saw",
        "allrounder": "achievement",
        "gym": "strong",
        "runner": "sprint",
        "iron": "armor-upgrade",
        "veteran": "laurels-trophy",
    ]

    /// One mark per muscle group, used in menus.
    static let category: [String: String] = [
        "PUSH": "muscle-up",
        "PULL": "weight-lifting-up",
        "LEGS": "boot-stomp",
        "CORE": "abdominal-armor",
        "CARDIO": "run",
        "SPORT": "soccer-ball",
        "GYM": "weight-lifting-up",
        "RECOVERY": "meditation",
    ]
}
